input CreateFileInput {
  createdAt: DateTime
  updatedAt: DateTime
  caption: String
  name: String!
  content: String!
  createdByID: ID
  updatedByID: ID
}

input CreateOneFileInput {
    create: CreateFileInput
    connect: FileWhereUniqueInput
}

input CreateManyFileInput {
    create: [CreateFileInput!]
    connect: [FileWhereUniqueInput!]
}


input UpdateOneFileInput {
    create: CreateFileInput
    connect: FileWhereUniqueInput
    delete: Boolean
    unset: Boolean
}

input UpdateManyFileInput {
    create: [CreateFileInput!]
    connect: [FileWhereUniqueInput!]
    delete: [FileWhereUniqueInput!]
    disconnect: [FileWhereUniqueInput!]
}

input CreateOneAdminUserInput {
    connect: AdminUserWhereUniqueInput
}

input CreateManyAdminUserInput {
    connect: [AdminUserWhereUniqueInput!]
}

input UpdateOneAdminUserInput {
    connect: AdminUserWhereUniqueInput
    unset: Boolean
}

input UpdateManyAdminUserInput {
    connect: [AdminUserWhereUniqueInput!]
    disconnect: [AdminUserWhereUniqueInput!]
}

input CreateOneRoleInput {
    connect: RoleWhereUniqueInput
}

input CreateManyRoleInput {
    connect: [RoleWhereUniqueInput!]
}

input UpdateOneRoleInput {
    connect: RoleWhereUniqueInput
    unset: Boolean
}

input UpdateManyRoleInput {
    connect: [RoleWhereUniqueInput!]
    disconnect: [RoleWhereUniqueInput!]
}

extend type AdminUser {
  name: String
  email: String!
  firstName: String!
  lastName: String!
  createdAt: Time
  updatedAt: Time
  createdBy: AdminUser
  updatedBy: AdminUser
  roles: [Role!]
  defaultRole: Role
}
extend type File {
  createdAt: DateTime
  updatedAt: DateTime
  caption: String
  name: String!
  mimeType: String!
  storageFileName: String!
  size: Int!
  content: String!
  createdBy: AdminUser
  updatedBy: AdminUser
}

extend type Role {
  createdAt: Time
  updatedAt: Time
  createdBy: AdminUser
  updatedBy: AdminUser
  AdminUserRoles: [AdminUser!]
  permissions: [Permission!]
}

type Permission implements Node {
  id: ID!
  createdAt: DateTime
  updatedAt: DateTime
  entity: String!
  operation: String!
  createdBy: AdminUser
  updatedBy: AdminUser
  role: Role
}
extend type Mutation {
    updateAdminUserPassword(where: AdminUserWhereUniqueInput!, password: String!): AdminUser!
}
scalar Time