extend type Query {
    users(where: UserWhereInput, orderBy: UserOrder, skip: Int, first: Int, last: Int): [User!]
    usersConnection(where: UserWhereInput, orderBy: UserOrder, skip: Int, first: Int, last: Int): UserConnection!
}
extend type Mutation {
    createUser(data: CreateUserInput!): User!
    createManyUsers(data: [CreateUserInput!]!): [User]!
    updateUser(where: UserWhereUniqueInput!, data: UpdateUserInput!): User!
    updateManyUsers(where: UserWhereInput!, data: UpdateUserInput!): Int!
    upsertUser(data: CreateUserInput!): User!
    upsertManyUsers(data: [CreateUserInput!]!): Int!
    deleteUser(where: UserWhereUniqueInput!): User!
    deleteManyUsers(where: UserWhereInput!): Int!
}
extend input CreateUserInput {
    refCreatedBy: CreateManyUserInput
    createdBy: CreateOneUserInput
    refUpdatedBy: CreateManyUserInput
    updatedBy: CreateOneUserInput
    adminCreatedBy: CreateOneAdminUserInput
    adminUpdatedBy: CreateOneAdminUserInput
    roles: CreateManyRoleInput
    defaultRole: CreateOneRoleInput
    refreshTokens: CreateManyUserRefreshTokenWithoutUserInput
}
extend input UpdateUserInput {
    refCreatedBy: UpdateManyUserInput
    createdBy: UpdateOneUserInput
    refUpdatedBy: UpdateManyUserInput
    updatedBy: UpdateOneUserInput
    adminCreatedBy: UpdateOneAdminUserInput
    adminUpdatedBy: UpdateOneAdminUserInput
    roles: UpdateManyRoleInput
    defaultRole: UpdateOneRoleInput
    refreshTokens: UpdateManyUserRefreshTokenWithoutUserInput
}

input CreateOneUserInput {
    create: CreateUserInput
    connect: UserWhereUniqueInput
}

input CreateManyUserInput {
    create: [CreateUserInput!]
    connect: [UserWhereUniqueInput!]
}


input UpdateOneUserInput {
    create: CreateUserInput
    connect: UserWhereUniqueInput
    delete: Boolean
    unset: Boolean
}

input UpdateManyUserInput {
    create: [CreateUserInput!]
    connect: [UserWhereUniqueInput!]
    delete: [UserWhereUniqueInput!]
    disconnect: [UserWhereUniqueInput!]
}
input CreateManyUserRefreshTokenWithoutUserInput {
    connect: [UserRefreshTokenWhereUniqueInput!]
    create: [CreateUserRefreshTokenWithoutUserInput!]
}
input CreateOneUserRefreshTokenWithoutUserInput {
    connect: UserRefreshTokenWhereUniqueInput
    create: CreateUserRefreshTokenWithoutUserInput
}
input CreateUserRefreshTokenWithoutUserInput {
    createdAt: Time!
    expiresAt: Time!
    revokedAt: Time
    tokenHash: String!
    updatedAt: Time!
    usedAt: Time
    user: CreateOneUserInput
}
