extend type Query {
    miaus(where: MiauWhereInput, orderBy: MiauOrder, skip: Int, first: Int, last: Int): [Miau!]
    miausConnection(where: MiauWhereInput, orderBy: MiauOrder, skip: Int, first: Int, last: Int): MiauConnection!
}
extend type Mutation {
    createMiau(data: CreateMiauInput!): Miau!
    createManyMiaus(data: [CreateMiauInput!]!): [Miau]!
    updateMiau(where: MiauWhereUniqueInput!, data: UpdateMiauInput!): Miau!
    updateManyMiaus(where: MiauWhereInput!, data: UpdateMiauInput!): Int!
    upsertMiau(data: CreateMiauInput!): Miau!
    upsertManyMiaus(data: [CreateMiauInput!]!): Int!
    deleteMiau(where: MiauWhereUniqueInput!): Miau!
    deleteManyMiaus(where: MiauWhereInput!): Int!
}
extend input CreateMiauInput {
    createdBy: CreateOneUserInput
    updatedBy: CreateOneUserInput
    adminCreatedBy: CreateOneAdminUserInput
    adminUpdatedBy: CreateOneAdminUserInput
}
extend input UpdateMiauInput {
    createdBy: UpdateOneUserInput
    updatedBy: UpdateOneUserInput
    adminCreatedBy: UpdateOneAdminUserInput
    adminUpdatedBy: UpdateOneAdminUserInput
}

input CreateOneMiauInput {
    create: CreateMiauInput
    connect: MiauWhereUniqueInput
}

input CreateManyMiauInput {
    create: [CreateMiauInput!]
    connect: [MiauWhereUniqueInput!]
}


input UpdateOneMiauInput {
    create: CreateMiauInput
    connect: MiauWhereUniqueInput
    delete: Boolean
    unset: Boolean
}

input UpdateManyMiauInput {
    create: [CreateMiauInput!]
    connect: [MiauWhereUniqueInput!]
    delete: [MiauWhereUniqueInput!]
    disconnect: [MiauWhereUniqueInput!]
}
