extend type Query {
    cycles(where: CycleWhereInput, orderBy: CycleOrder, skip: Int, first: Int, last: Int): [Cycle!]
    cyclesConnection(where: CycleWhereInput, orderBy: CycleOrder, skip: Int, first: Int, last: Int): CycleConnection!
}
extend type Mutation {
    createCycle(data: CreateCycleInput!): Cycle!
    createManyCycles(data: [CreateCycleInput!]!): [Cycle]!
    updateCycle(where: CycleWhereUniqueInput!, data: UpdateCycleInput!): Cycle!
    updateCycleState(where: CycleWhereUniqueInput!, state: EntityState!): Cycle!
    updateManyCycles(where: CycleWhereInput!, data: UpdateCycleInput!): Int!
    upsertCycle(data: CreateCycleInput!): Cycle!
    upsertManyCycles(data: [CreateCycleInput!]!): Int!
    deleteCycle(where: CycleWhereUniqueInput!): Cycle!
    deleteManyCycles(where: CycleWhereInput!): Int!
}
extend input CreateCycleInput {
    createdBy: CreateOneUserInput
    updatedBy: CreateOneUserInput
    adminCreatedBy: CreateOneAdminUserInput
    adminUpdatedBy: CreateOneAdminUserInput
}
extend input UpdateCycleInput {
    createdBy: UpdateOneUserInput
    updatedBy: UpdateOneUserInput
    adminCreatedBy: UpdateOneAdminUserInput
    adminUpdatedBy: UpdateOneAdminUserInput
}

input CreateOneCycleInput {
    create: CreateCycleInput
    connect: CycleWhereUniqueInput
}

input CreateManyCycleInput {
    create: [CreateCycleInput!]
    connect: [CycleWhereUniqueInput!]
}


input UpdateOneCycleInput {
    create: CreateCycleInput
    connect: CycleWhereUniqueInput
    delete: Boolean
    unset: Boolean
}

input UpdateManyCycleInput {
    create: [CreateCycleInput!]
    connect: [CycleWhereUniqueInput!]
    delete: [CycleWhereUniqueInput!]
    disconnect: [CycleWhereUniqueInput!]
}
