extend type Query {
    forPermissions(where: ForPermissionWhereInput, orderBy: ForPermissionOrder, skip: Int, first: Int, last: Int): [ForPermission!]
    forPermissionsConnection(where: ForPermissionWhereInput, orderBy: ForPermissionOrder, skip: Int, first: Int, last: Int): ForPermissionConnection!
}
extend type Mutation {
    createForPermission(data: CreateForPermissionInput!): ForPermission!
    createManyForPermissions(data: [CreateForPermissionInput!]!): [ForPermission]!
    updateForPermission(where: ForPermissionWhereUniqueInput!, data: UpdateForPermissionInput!): ForPermission!
    updateManyForPermissions(where: ForPermissionWhereInput!, data: UpdateForPermissionInput!): Int!
    upsertForPermission(data: CreateForPermissionInput!): ForPermission!
    upsertManyForPermissions(data: [CreateForPermissionInput!]!): Int!
    deleteForPermission(where: ForPermissionWhereUniqueInput!): ForPermission!
    deleteManyForPermissions(where: ForPermissionWhereInput!): Int!
}
extend input CreateForPermissionInput {
    createdBy: CreateOneUserInput
    updatedBy: CreateOneUserInput
    adminCreatedBy: CreateOneAdminUserInput
    adminUpdatedBy: CreateOneAdminUserInput
}
extend input UpdateForPermissionInput {
    createdBy: UpdateOneUserInput
    updatedBy: UpdateOneUserInput
    adminCreatedBy: UpdateOneAdminUserInput
    adminUpdatedBy: UpdateOneAdminUserInput
}

input CreateOneForPermissionInput {
    create: CreateForPermissionInput
    connect: ForPermissionWhereUniqueInput
}

input CreateManyForPermissionInput {
    create: [CreateForPermissionInput!]
    connect: [ForPermissionWhereUniqueInput!]
}


input UpdateOneForPermissionInput {
    create: CreateForPermissionInput
    connect: ForPermissionWhereUniqueInput
    delete: Boolean
    unset: Boolean
}

input UpdateManyForPermissionInput {
    create: [CreateForPermissionInput!]
    connect: [ForPermissionWhereUniqueInput!]
    delete: [ForPermissionWhereUniqueInput!]
    disconnect: [ForPermissionWhereUniqueInput!]
}
