package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"app/ent"
	"app/generated"
	"context"
)

// CreateForPermission is the resolver for the createForPermission field.
func (r *mutationResolver) CreateForPermission(ctx context.Context, data ent.CreateForPermissionInput) (*ent.ForPermission, error) {
	return r.Service.ForPermission.Create(ctx, data)
}

// CreateManyForPermissions is the resolver for the createManyForPermissions field.
func (r *mutationResolver) CreateManyForPermissions(ctx context.Context, data []*ent.CreateForPermissionInput) ([]*ent.ForPermission, error) {
	var dataVal []ent.CreateForPermissionInput
	for _, createInput := range data {
		dataVal = append(dataVal, *createInput)
	}
	return r.Service.ForPermission.CreateMany(ctx, dataVal)
}

// UpdateForPermission is the resolver for the updateForPermission field.
func (r *mutationResolver) UpdateForPermission(ctx context.Context, where ent.ForPermissionWhereUniqueInput, data ent.UpdateForPermissionInput) (*ent.ForPermission, error) {
	return r.Service.ForPermission.Update(ctx, where, data)
}

// UpdateManyForPermissions is the resolver for the updateManyForPermissions field.
func (r *mutationResolver) UpdateManyForPermissions(ctx context.Context, where ent.ForPermissionWhereInput, data ent.UpdateForPermissionInput) (int, error) {
	return r.Service.ForPermission.UpdateMany(ctx, where, data)
}

// UpsertForPermission is the resolver for the upsertForPermission field.
func (r *mutationResolver) UpsertForPermission(ctx context.Context, data ent.CreateForPermissionInput) (*ent.ForPermission, error) {
	return r.Service.ForPermission.Upsert(ctx, data)
}

// UpsertManyForPermissions is the resolver for the upsertManyForPermissions field.
func (r *mutationResolver) UpsertManyForPermissions(ctx context.Context, data []*ent.CreateForPermissionInput) (int, error) {
	var dataVal []ent.CreateForPermissionInput
	for _, upsertInput := range data {
		dataVal = append(dataVal, *upsertInput)
	}
	return r.Service.ForPermission.UpsertMany(ctx, dataVal)
}

// DeleteForPermission is the resolver for the deleteForPermission field.
func (r *mutationResolver) DeleteForPermission(ctx context.Context, where ent.ForPermissionWhereUniqueInput) (*ent.ForPermission, error) {
	return r.Service.ForPermission.Delete(ctx, where)
}

// DeleteManyForPermissions is the resolver for the deleteManyForPermissions field.
func (r *mutationResolver) DeleteManyForPermissions(ctx context.Context, where ent.ForPermissionWhereInput) (int, error) {
	return r.Service.ForPermission.DeleteMany(ctx, where)
}

// ForPermissions is the resolver for the forPermissions field.
func (r *queryResolver) ForPermissions(ctx context.Context, where *ent.ForPermissionWhereInput, orderBy *ent.ForPermissionOrder, skip *int, first *int, last *int) ([]*ent.ForPermission, error) {
	return r.Service.ForPermission.Get(ctx, where, orderBy, skip, first, last)
}

// ForPermissionsConnection is the resolver for the forPermissionsConnection field.
func (r *queryResolver) ForPermissionsConnection(ctx context.Context, where *ent.ForPermissionWhereInput, orderBy *ent.ForPermissionOrder, skip *int, first *int, last *int) (*ent.ForPermissionConnection, error) {
	return r.Service.ForPermission.Connection(ctx, where, orderBy, skip, first, last)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *forPermissionResolver) AdminCreatedBy(ctx context.Context, obj *ent.ForPermission) (*ent1.AdminUser, error) {
	relObj, err := obj.AdminCreatedBy(ctx)
	if err != nil {
		return nil, fmt.Errorf("[forPermissionResolver.admin_created_by]: %w", err)
	}
	if relObj == nil {
		return nil, nil
	}

	adminObj, err := r.Service.AdminUser.GetOne(ctx, ent1.AdminUserWhereUniqueInput{ID: &relObj.ID})
	if err != nil {
		return nil, fmt.Errorf("[forPermissionResolver. AdminCreatedBy]: %w", err)
	}

	return adminObj, nil
}
func (r *forPermissionResolver) AdminUpdatedBy(ctx context.Context, obj *ent.ForPermission) (*ent1.AdminUser, error) {
	relObj, err := obj.AdminUpdatedBy(ctx)
	if err != nil {
		return nil, fmt.Errorf("[forPermissionResolver.admin_updated_by]: %w", err)
	}
	if relObj == nil {
		return nil, nil
	}

	adminObj, err := r.Service.AdminUser.GetOne(ctx, ent1.AdminUserWhereUniqueInput{ID: &relObj.ID})
	if err != nil {
		return nil, fmt.Errorf("[forPermissionResolver. AdminUpdatedBy]: %w", err)
	}

	return adminObj, nil
}
*/
