export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  Cursor: { input: any; output: any; }
  DateOnly: { input: any; output: any; }
  DateTime: { input: any; output: any; }
  Time: { input: any; output: any; }
  TimeOnly: { input: any; output: any; }
};

export type AdminUser = Node & {
  __typename?: 'AdminUser';
  adminCreatedBy?: Maybe<AdminUser>;
  adminUpdatedBy?: Maybe<AdminUser>;
  createdAt?: Maybe<Scalars['Time']['output']>;
  defaultRole?: Maybe<Role>;
  email: Scalars['String']['output'];
  firstName: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  lastName: Scalars['String']['output'];
  name?: Maybe<Scalars['String']['output']>;
  password: Scalars['String']['output'];
  refAdminUpdatedBy?: Maybe<Array<AdminUser>>;
  roles?: Maybe<Array<Role>>;
  updatedAt?: Maybe<Scalars['Time']['output']>;
};

/** A connection to a list of items. */
export type AdminUserConnection = {
  __typename?: 'AdminUserConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<AdminUserEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type AdminUserEdge = {
  __typename?: 'AdminUserEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<AdminUser>;
};

/** Ordering options for AdminUser connections */
export type AdminUserOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order AdminUsers. */
  field: AdminUserOrderField;
};

/** Properties by which AdminUser connections can be ordered. */
export enum AdminUserOrderField {
  CreatedAt = 'createdAt',
  Email = 'email',
  FirstName = 'firstName',
  Id = 'id',
  LastName = 'lastName',
  Name = 'name',
  UpdatedAt = 'updatedAt'
}

/**
 * AdminUserWhereInput is used for filtering AdminUser objects.
 * Input was generated by ent.
 */
export type AdminUserWhereInput = {
  and?: InputMaybe<Array<AdminUserWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** email field predicates */
  email?: InputMaybe<Scalars['String']['input']>;
  emailContains?: InputMaybe<Scalars['String']['input']>;
  emailContainsFold?: InputMaybe<Scalars['String']['input']>;
  emailEqualFold?: InputMaybe<Scalars['String']['input']>;
  emailGT?: InputMaybe<Scalars['String']['input']>;
  emailGTE?: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix?: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix?: InputMaybe<Scalars['String']['input']>;
  emailIn?: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT?: InputMaybe<Scalars['String']['input']>;
  emailLTE?: InputMaybe<Scalars['String']['input']>;
  emailNEQ?: InputMaybe<Scalars['String']['input']>;
  emailNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** first_name field predicates */
  firstName?: InputMaybe<Scalars['String']['input']>;
  firstNameContains?: InputMaybe<Scalars['String']['input']>;
  firstNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  firstNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  firstNameGT?: InputMaybe<Scalars['String']['input']>;
  firstNameGTE?: InputMaybe<Scalars['String']['input']>;
  firstNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  firstNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  firstNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  firstNameLT?: InputMaybe<Scalars['String']['input']>;
  firstNameLTE?: InputMaybe<Scalars['String']['input']>;
  firstNameNEQ?: InputMaybe<Scalars['String']['input']>;
  firstNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** admin_created_by edge predicates */
  hasAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminCreatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_updated_by edge predicates */
  hasAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** default_role edge predicates */
  hasDefaultRole?: InputMaybe<Scalars['Boolean']['input']>;
  hasDefaultRoleWith?: InputMaybe<Array<RoleWhereInput>>;
  /** ref_admin_updated_by edge predicates */
  hasRefAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasRefAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** roles edge predicates */
  hasRoles?: InputMaybe<Scalars['Boolean']['input']>;
  hasRolesWith?: InputMaybe<Array<RoleWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idContainsFold?: InputMaybe<Scalars['ID']['input']>;
  idEqualFold?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** last_name field predicates */
  lastName?: InputMaybe<Scalars['String']['input']>;
  lastNameContains?: InputMaybe<Scalars['String']['input']>;
  lastNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  lastNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  lastNameGT?: InputMaybe<Scalars['String']['input']>;
  lastNameGTE?: InputMaybe<Scalars['String']['input']>;
  lastNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  lastNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  lastNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  lastNameLT?: InputMaybe<Scalars['String']['input']>;
  lastNameLTE?: InputMaybe<Scalars['String']['input']>;
  lastNameNEQ?: InputMaybe<Scalars['String']['input']>;
  lastNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  not?: InputMaybe<AdminUserWhereInput>;
  or?: InputMaybe<Array<AdminUserWhereInput>>;
  /** password field predicates */
  password?: InputMaybe<Scalars['String']['input']>;
  passwordContains?: InputMaybe<Scalars['String']['input']>;
  passwordContainsFold?: InputMaybe<Scalars['String']['input']>;
  passwordEqualFold?: InputMaybe<Scalars['String']['input']>;
  passwordGT?: InputMaybe<Scalars['String']['input']>;
  passwordGTE?: InputMaybe<Scalars['String']['input']>;
  passwordHasPrefix?: InputMaybe<Scalars['String']['input']>;
  passwordHasSuffix?: InputMaybe<Scalars['String']['input']>;
  passwordIn?: InputMaybe<Array<Scalars['String']['input']>>;
  passwordLT?: InputMaybe<Scalars['String']['input']>;
  passwordLTE?: InputMaybe<Scalars['String']['input']>;
  passwordNEQ?: InputMaybe<Scalars['String']['input']>;
  passwordNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** updated_at field predicates */
  updatedAt?: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT?: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  updatedAtLT?: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AdminUserWhereUniqueInput = {
  email?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
};

export enum AppStatus {
  Fatal = 'FATAL',
  Generating = 'GENERATING',
  Restarting = 'RESTARTING',
  Reverting = 'REVERTING',
  Up = 'UP'
}

/**
 * CreateAdminUserInput is used for create AdminUser object.
 * Input was generated by ent.
 */
export type CreateAdminUserInput = {
  adminCreatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminUpdatedBy?: InputMaybe<CreateOneAdminUserInput>;
  defaultRole?: InputMaybe<CreateOneRoleInput>;
  defaultRoleID?: InputMaybe<Scalars['ID']['input']>;
  email: Scalars['String']['input'];
  firstName: Scalars['String']['input'];
  lastName: Scalars['String']['input'];
  name?: InputMaybe<Scalars['String']['input']>;
  password: Scalars['String']['input'];
  refAdminCreatedBy?: InputMaybe<CreateManyAdminUserInput>;
  refAdminUpdatedBy?: InputMaybe<CreateManyAdminUserInput>;
  roleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  roles?: InputMaybe<CreateManyRoleInput>;
};

export type CreateEdgeInput = {
  belongsToCaption?: InputMaybe<Scalars['String']['input']>;
  caption: Scalars['String']['input'];
  private?: InputMaybe<Scalars['Boolean']['input']>;
  relatedEntity: EntityConnectInput;
  relationType: RelationType;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type CreateEntityInput = {
  caption: Scalars['String']['input'];
  displayField: FieldWhereUniqueInput;
  edges?: InputMaybe<CreateManyEdgesInput>;
  fields?: InputMaybe<CreateManyFieldsInput>;
};

export type CreateFieldInput = {
  acceptedValues?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  caption: Scalars['String']['input'];
  defaultValue?: InputMaybe<Scalars['String']['input']>;
  max?: InputMaybe<Scalars['String']['input']>;
  min?: InputMaybe<Scalars['String']['input']>;
  private?: InputMaybe<Scalars['Boolean']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
  type: Scalars['String']['input'];
  unique?: InputMaybe<Scalars['Boolean']['input']>;
};

/**
 * CreateFileInput is used for create File object.
 * Input was generated by ent.
 */
export type CreateFileInput = {
  adminCreatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminCreatedByID?: InputMaybe<Scalars['ID']['input']>;
  adminUpdatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminUpdatedByID?: InputMaybe<Scalars['ID']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  createdBy?: InputMaybe<CreateOneUserInput>;
  createdByID?: InputMaybe<Scalars['ID']['input']>;
  mimeType: Scalars['String']['input'];
  name: Scalars['String']['input'];
  size: Scalars['Int']['input'];
  storageFileName: Scalars['String']['input'];
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
  updatedBy?: InputMaybe<CreateOneUserInput>;
  updatedByID?: InputMaybe<Scalars['ID']['input']>;
};

export type CreateManyAdminUserInput = {
  connect?: InputMaybe<Array<AdminUserWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateAdminUserInput>>;
};

export type CreateManyEdgesInput = {
  create?: InputMaybe<Array<CreateEdgeInput>>;
};

export type CreateManyFieldsInput = {
  create?: InputMaybe<Array<CreateFieldInput>>;
};

export type CreateManyFileInput = {
  connect?: InputMaybe<Array<FileWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateFileInput>>;
};

export type CreateManyPermissionInput = {
  connect?: InputMaybe<Array<PermissionWhereUniqueInput>>;
  create?: InputMaybe<Array<CreatePermissionInput>>;
};

export type CreateManyRoleInput = {
  connect?: InputMaybe<Array<RoleWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateRoleInput>>;
};

export type CreateManyUserInput = {
  connect?: InputMaybe<Array<UserWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateUserInput>>;
};

export type CreateOneAdminUserInput = {
  connect?: InputMaybe<AdminUserWhereUniqueInput>;
  create?: InputMaybe<CreateAdminUserInput>;
};

export type CreateOneFileInput = {
  connect?: InputMaybe<FileWhereUniqueInput>;
  create?: InputMaybe<CreateFileInput>;
};

export type CreateOnePermissionInput = {
  connect?: InputMaybe<PermissionWhereUniqueInput>;
  create?: InputMaybe<CreatePermissionInput>;
};

export type CreateOneRoleInput = {
  connect?: InputMaybe<RoleWhereUniqueInput>;
  create?: InputMaybe<CreateRoleInput>;
};

export type CreateOneUserInput = {
  connect?: InputMaybe<UserWhereUniqueInput>;
  create?: InputMaybe<CreateUserInput>;
};

/**
 * CreatePermissionInput is used for create Permission object.
 * Input was generated by ent.
 */
export type CreatePermissionInput = {
  adminCreatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminCreatedByID?: InputMaybe<Scalars['ID']['input']>;
  adminUpdatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminUpdatedByID?: InputMaybe<Scalars['ID']['input']>;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  entity: Scalars['String']['input'];
  operation?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<CreateOneRoleInput>;
  roleID?: InputMaybe<Scalars['ID']['input']>;
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
};

/**
 * CreateRoleInput is used for create Role object.
 * Input was generated by ent.
 */
export type CreateRoleInput = {
  adminCreatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminUpdatedBy?: InputMaybe<CreateOneAdminUserInput>;
  adminUserRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  name: Scalars['String']['input'];
  permissionIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  permissions?: InputMaybe<CreateManyPermissionInput>;
  userRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  userRoles?: InputMaybe<CreateManyAdminUserInput>;
};

/**
 * CreateUserInput is used for create User object.
 * Input was generated by ent.
 */
export type CreateUserInput = {
  createdBy?: InputMaybe<CreateOneUserInput>;
  defaultRole?: InputMaybe<CreateOneRoleInput>;
  defaultRoleID?: InputMaybe<Scalars['ID']['input']>;
  email: Scalars['String']['input'];
  password: Scalars['String']['input'];
  refCreatedBy?: InputMaybe<CreateManyUserInput>;
  refUpdatedBy?: InputMaybe<CreateManyUserInput>;
  roleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  roles?: InputMaybe<CreateManyRoleInput>;
  updatedBy?: InputMaybe<CreateOneUserInput>;
};

export type Edge = {
  __typename?: 'Edge';
  belongsToCaption?: Maybe<Scalars['String']['output']>;
  caption: Scalars['String']['output'];
  name: Scalars['String']['output'];
  private?: Maybe<Scalars['Boolean']['output']>;
  relatedEntity: Entity;
  relationType?: Maybe<RelationType>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type EdgeWhereUniqueInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type Entity = {
  __typename?: 'Entity';
  caption: Scalars['String']['output'];
  df: Scalars['String']['output'];
  displayField: Field;
  edges?: Maybe<Array<Edge>>;
  fields?: Maybe<Array<Field>>;
  name: Scalars['String']['output'];
  owner: EntityOwner;
  pluralName: Scalars['String']['output'];
};

export type EntityConnectInput = {
  connect: EntityWhereUniqueInput;
};

export enum EntityOwner {
  Admin = 'Admin',
  User = 'User'
}

export type EntityWhereUniqueInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type Field = {
  __typename?: 'Field';
  acceptedValues?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  caption: Scalars['String']['output'];
  defaultValue?: Maybe<Scalars['String']['output']>;
  max?: Maybe<Scalars['String']['output']>;
  min?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  private?: Maybe<Scalars['Boolean']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
  type: Scalars['String']['output'];
  unique?: Maybe<Scalars['Boolean']['output']>;
};

export type FieldWhereUniqueInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type File = Node & {
  __typename?: 'File';
  adminCreatedBy?: Maybe<AdminUser>;
  adminUpdatedBy?: Maybe<AdminUser>;
  caption?: Maybe<Scalars['String']['output']>;
  createdAt?: Maybe<Scalars['DateTime']['output']>;
  createdBy?: Maybe<User>;
  id: Scalars['ID']['output'];
  mimeType: Scalars['String']['output'];
  name: Scalars['String']['output'];
  size: Scalars['Int']['output'];
  storageFileName: Scalars['String']['output'];
  updatedAt?: Maybe<Scalars['DateTime']['output']>;
  updatedBy?: Maybe<User>;
};

/** A connection to a list of items. */
export type FileConnection = {
  __typename?: 'FileConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<FileEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type FileEdge = {
  __typename?: 'FileEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<File>;
};

/** Ordering options for File connections */
export type FileOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Files. */
  field: FileOrderField;
};

/** Properties by which File connections can be ordered. */
export enum FileOrderField {
  Caption = 'caption',
  CreatedAt = 'createdAt',
  Id = 'id',
  MimeType = 'mimeType',
  Name = 'name',
  Size = 'size',
  StorageFileName = 'storageFileName',
  UpdatedAt = 'updatedAt'
}

/**
 * FileWhereInput is used for filtering File objects.
 * Input was generated by ent.
 */
export type FileWhereInput = {
  and?: InputMaybe<Array<FileWhereInput>>;
  /** caption field predicates */
  caption?: InputMaybe<Scalars['String']['input']>;
  captionContains?: InputMaybe<Scalars['String']['input']>;
  captionContainsFold?: InputMaybe<Scalars['String']['input']>;
  captionEqualFold?: InputMaybe<Scalars['String']['input']>;
  captionGT?: InputMaybe<Scalars['String']['input']>;
  captionGTE?: InputMaybe<Scalars['String']['input']>;
  captionHasPrefix?: InputMaybe<Scalars['String']['input']>;
  captionHasSuffix?: InputMaybe<Scalars['String']['input']>;
  captionIn?: InputMaybe<Array<Scalars['String']['input']>>;
  captionIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  captionLT?: InputMaybe<Scalars['String']['input']>;
  captionLTE?: InputMaybe<Scalars['String']['input']>;
  captionNEQ?: InputMaybe<Scalars['String']['input']>;
  captionNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  captionNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtGT?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtGTE?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  createdAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  createdAtLT?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtLTE?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  createdAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** admin_created_by edge predicates */
  hasAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminCreatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_updated_by edge predicates */
  hasAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** created_by edge predicates */
  hasCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasCreatedByWith?: InputMaybe<Array<UserWhereInput>>;
  /** updated_by edge predicates */
  hasUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasUpdatedByWith?: InputMaybe<Array<UserWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idContainsFold?: InputMaybe<Scalars['ID']['input']>;
  idEqualFold?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** mime_type field predicates */
  mimeType?: InputMaybe<Scalars['String']['input']>;
  mimeTypeContains?: InputMaybe<Scalars['String']['input']>;
  mimeTypeContainsFold?: InputMaybe<Scalars['String']['input']>;
  mimeTypeEqualFold?: InputMaybe<Scalars['String']['input']>;
  mimeTypeGT?: InputMaybe<Scalars['String']['input']>;
  mimeTypeGTE?: InputMaybe<Scalars['String']['input']>;
  mimeTypeHasPrefix?: InputMaybe<Scalars['String']['input']>;
  mimeTypeHasSuffix?: InputMaybe<Scalars['String']['input']>;
  mimeTypeIn?: InputMaybe<Array<Scalars['String']['input']>>;
  mimeTypeLT?: InputMaybe<Scalars['String']['input']>;
  mimeTypeLTE?: InputMaybe<Scalars['String']['input']>;
  mimeTypeNEQ?: InputMaybe<Scalars['String']['input']>;
  mimeTypeNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<FileWhereInput>;
  or?: InputMaybe<Array<FileWhereInput>>;
  /** size field predicates */
  size?: InputMaybe<Scalars['Int']['input']>;
  sizeGT?: InputMaybe<Scalars['Int']['input']>;
  sizeGTE?: InputMaybe<Scalars['Int']['input']>;
  sizeIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  sizeLT?: InputMaybe<Scalars['Int']['input']>;
  sizeLTE?: InputMaybe<Scalars['Int']['input']>;
  sizeNEQ?: InputMaybe<Scalars['Int']['input']>;
  sizeNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  /** storage_file_name field predicates */
  storageFileName?: InputMaybe<Scalars['String']['input']>;
  storageFileNameContains?: InputMaybe<Scalars['String']['input']>;
  storageFileNameContainsFold?: InputMaybe<Scalars['String']['input']>;
  storageFileNameEqualFold?: InputMaybe<Scalars['String']['input']>;
  storageFileNameGT?: InputMaybe<Scalars['String']['input']>;
  storageFileNameGTE?: InputMaybe<Scalars['String']['input']>;
  storageFileNameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  storageFileNameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  storageFileNameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  storageFileNameLT?: InputMaybe<Scalars['String']['input']>;
  storageFileNameLTE?: InputMaybe<Scalars['String']['input']>;
  storageFileNameNEQ?: InputMaybe<Scalars['String']['input']>;
  storageFileNameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** updated_at field predicates */
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtGT?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtGTE?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  updatedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  updatedAtLT?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtLTE?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtNEQ?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtNotIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  updatedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FileWhereUniqueInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createAdminUser: AdminUser;
  createEntity: Entity;
  createFile: File;
  createManyAdminUsers: Array<Maybe<AdminUser>>;
  createManyFiles: Array<Maybe<File>>;
  createManyPermissions: Array<Maybe<Permission>>;
  createManyRoles: Array<Maybe<Role>>;
  createManyUsers: Array<Maybe<User>>;
  createPermission: Permission;
  createRole: Role;
  createUser: User;
  deleteAdminUser: AdminUser;
  deleteEntity: Entity;
  deleteFile: File;
  deleteManyAdminUsers: Scalars['Int']['output'];
  deleteManyFiles: Scalars['Int']['output'];
  deleteManyPermissions: Scalars['Int']['output'];
  deleteManyRoles: Scalars['Int']['output'];
  deleteManyUsers: Scalars['Int']['output'];
  deletePermission: Permission;
  deleteRole: Role;
  deleteUser: User;
  updateAdminUser: AdminUser;
  updateEntity: Entity;
  updateFile: File;
  updateManyAdminUsers: Scalars['Int']['output'];
  updateManyFiles: Scalars['Int']['output'];
  updateManyPermissions: Scalars['Int']['output'];
  updateManyRoles: Scalars['Int']['output'];
  updateManyUsers: Scalars['Int']['output'];
  updatePermission: Permission;
  updateRole: Role;
  updateUser: User;
  upsertAdminUser: AdminUser;
  upsertFile: File;
  upsertManyAdminUsers: Scalars['Int']['output'];
  upsertManyFiles: Scalars['Int']['output'];
  upsertManyPermissions: Scalars['Int']['output'];
  upsertManyRoles: Scalars['Int']['output'];
  upsertManyUsers: Scalars['Int']['output'];
  upsertPermission: Permission;
  upsertRole: Role;
  upsertUser: User;
};


export type MutationCreateAdminUserArgs = {
  data: CreateAdminUserInput;
};


export type MutationCreateEntityArgs = {
  data: CreateEntityInput;
};


export type MutationCreateFileArgs = {
  data: CreateFileInput;
};


export type MutationCreateManyAdminUsersArgs = {
  data: Array<CreateAdminUserInput>;
};


export type MutationCreateManyFilesArgs = {
  data: Array<CreateFileInput>;
};


export type MutationCreateManyPermissionsArgs = {
  data: Array<CreatePermissionInput>;
};


export type MutationCreateManyRolesArgs = {
  data: Array<CreateRoleInput>;
};


export type MutationCreateManyUsersArgs = {
  data: Array<CreateUserInput>;
};


export type MutationCreatePermissionArgs = {
  data: CreatePermissionInput;
};


export type MutationCreateRoleArgs = {
  data: CreateRoleInput;
};


export type MutationCreateUserArgs = {
  data: CreateUserInput;
};


export type MutationDeleteAdminUserArgs = {
  where: AdminUserWhereUniqueInput;
};


export type MutationDeleteEntityArgs = {
  where: EntityWhereUniqueInput;
};


export type MutationDeleteFileArgs = {
  where: FileWhereUniqueInput;
};


export type MutationDeleteManyAdminUsersArgs = {
  where: AdminUserWhereInput;
};


export type MutationDeleteManyFilesArgs = {
  where: FileWhereInput;
};


export type MutationDeleteManyPermissionsArgs = {
  where: PermissionWhereInput;
};


export type MutationDeleteManyRolesArgs = {
  where: RoleWhereInput;
};


export type MutationDeleteManyUsersArgs = {
  where: UserWhereInput;
};


export type MutationDeletePermissionArgs = {
  where: PermissionWhereUniqueInput;
};


export type MutationDeleteRoleArgs = {
  where: RoleWhereUniqueInput;
};


export type MutationDeleteUserArgs = {
  where: UserWhereUniqueInput;
};


export type MutationUpdateAdminUserArgs = {
  data: UpdateAdminUserInput;
  where: AdminUserWhereUniqueInput;
};


export type MutationUpdateEntityArgs = {
  data: UpdateEntityInput;
  where: EntityWhereUniqueInput;
};


export type MutationUpdateFileArgs = {
  data: UpdateFileInput;
  where: FileWhereUniqueInput;
};


export type MutationUpdateManyAdminUsersArgs = {
  data: UpdateAdminUserInput;
  where: AdminUserWhereInput;
};


export type MutationUpdateManyFilesArgs = {
  data: UpdateFileInput;
  where: FileWhereInput;
};


export type MutationUpdateManyPermissionsArgs = {
  data: UpdatePermissionInput;
  where: PermissionWhereInput;
};


export type MutationUpdateManyRolesArgs = {
  data: UpdateRoleInput;
  where: RoleWhereInput;
};


export type MutationUpdateManyUsersArgs = {
  data: UpdateUserInput;
  where: UserWhereInput;
};


export type MutationUpdatePermissionArgs = {
  data: UpdatePermissionInput;
  where: PermissionWhereUniqueInput;
};


export type MutationUpdateRoleArgs = {
  data: UpdateRoleInput;
  where: RoleWhereUniqueInput;
};


export type MutationUpdateUserArgs = {
  data: UpdateUserInput;
  where: UserWhereUniqueInput;
};


export type MutationUpsertAdminUserArgs = {
  data: CreateAdminUserInput;
};


export type MutationUpsertFileArgs = {
  data: CreateFileInput;
};


export type MutationUpsertManyAdminUsersArgs = {
  data: Array<CreateAdminUserInput>;
};


export type MutationUpsertManyFilesArgs = {
  data: Array<CreateFileInput>;
};


export type MutationUpsertManyPermissionsArgs = {
  data: Array<CreatePermissionInput>;
};


export type MutationUpsertManyRolesArgs = {
  data: Array<CreateRoleInput>;
};


export type MutationUpsertManyUsersArgs = {
  data: Array<CreateUserInput>;
};


export type MutationUpsertPermissionArgs = {
  data: CreatePermissionInput;
};


export type MutationUpsertRoleArgs = {
  data: CreateRoleInput;
};


export type MutationUpsertUserArgs = {
  data: CreateUserInput;
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID']['output'];
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['Cursor']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['Cursor']['output']>;
};

export type Permission = Node & {
  __typename?: 'Permission';
  adminCreatedBy?: Maybe<AdminUser>;
  adminUpdatedBy?: Maybe<AdminUser>;
  createdAt?: Maybe<Scalars['DateTime']['output']>;
  entity: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  operation: Scalars['String']['output'];
  role?: Maybe<Role>;
  updatedAt?: Maybe<Scalars['DateTime']['output']>;
};

/** A connection to a list of items. */
export type PermissionConnection = {
  __typename?: 'PermissionConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<PermissionEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type PermissionEdge = {
  __typename?: 'PermissionEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Permission>;
};

/** Ordering options for Permission connections */
export type PermissionOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Permissions. */
  field: PermissionOrderField;
};

/** Properties by which Permission connections can be ordered. */
export enum PermissionOrderField {
  Entity = 'entity',
  Id = 'id',
  Operation = 'operation'
}

/**
 * PermissionWhereInput is used for filtering Permission objects.
 * Input was generated by ent.
 */
export type PermissionWhereInput = {
  and?: InputMaybe<Array<PermissionWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtGT?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtGTE?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  createdAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  createdAtLT?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtLTE?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['DateTime']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  createdAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** entity field predicates */
  entity?: InputMaybe<Scalars['String']['input']>;
  entityContains?: InputMaybe<Scalars['String']['input']>;
  entityContainsFold?: InputMaybe<Scalars['String']['input']>;
  entityEqualFold?: InputMaybe<Scalars['String']['input']>;
  entityGT?: InputMaybe<Scalars['String']['input']>;
  entityGTE?: InputMaybe<Scalars['String']['input']>;
  entityHasPrefix?: InputMaybe<Scalars['String']['input']>;
  entityHasSuffix?: InputMaybe<Scalars['String']['input']>;
  entityIn?: InputMaybe<Array<Scalars['String']['input']>>;
  entityLT?: InputMaybe<Scalars['String']['input']>;
  entityLTE?: InputMaybe<Scalars['String']['input']>;
  entityNEQ?: InputMaybe<Scalars['String']['input']>;
  entityNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** admin_created_by edge predicates */
  hasAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminCreatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_updated_by edge predicates */
  hasAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** role edge predicates */
  hasRole?: InputMaybe<Scalars['Boolean']['input']>;
  hasRoleWith?: InputMaybe<Array<RoleWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idContainsFold?: InputMaybe<Scalars['ID']['input']>;
  idEqualFold?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<PermissionWhereInput>;
  /** operation field predicates */
  operation?: InputMaybe<Scalars['String']['input']>;
  operationContains?: InputMaybe<Scalars['String']['input']>;
  operationContainsFold?: InputMaybe<Scalars['String']['input']>;
  operationEqualFold?: InputMaybe<Scalars['String']['input']>;
  operationGT?: InputMaybe<Scalars['String']['input']>;
  operationGTE?: InputMaybe<Scalars['String']['input']>;
  operationHasPrefix?: InputMaybe<Scalars['String']['input']>;
  operationHasSuffix?: InputMaybe<Scalars['String']['input']>;
  operationIn?: InputMaybe<Array<Scalars['String']['input']>>;
  operationLT?: InputMaybe<Scalars['String']['input']>;
  operationLTE?: InputMaybe<Scalars['String']['input']>;
  operationNEQ?: InputMaybe<Scalars['String']['input']>;
  operationNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  or?: InputMaybe<Array<PermissionWhereInput>>;
  /** updated_at field predicates */
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtGT?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtGTE?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  updatedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  updatedAtLT?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtLTE?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtNEQ?: InputMaybe<Scalars['DateTime']['input']>;
  updatedAtNotIn?: InputMaybe<Array<Scalars['DateTime']['input']>>;
  updatedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PermissionWhereUniqueInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
};

export type Query = {
  __typename?: 'Query';
  adminUsers?: Maybe<Array<AdminUser>>;
  adminUsersConnection: AdminUserConnection;
  entities?: Maybe<Array<Entity>>;
  entity?: Maybe<Entity>;
  fields?: Maybe<Array<Field>>;
  files?: Maybe<Array<File>>;
  filesConnection: FileConnection;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  permissions?: Maybe<Array<Permission>>;
  permissionsConnection: PermissionConnection;
  roles?: Maybe<Array<Role>>;
  rolesConnection: RoleConnection;
  users?: Maybe<Array<User>>;
  usersConnection: UserConnection;
};


export type QueryAdminUsersArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<AdminUserOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<AdminUserWhereInput>;
};


export type QueryAdminUsersConnectionArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<AdminUserOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<AdminUserWhereInput>;
};


export type QueryEntityArgs = {
  where?: InputMaybe<EntityWhereUniqueInput>;
};


export type QueryFilesArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<FileOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<FileWhereInput>;
};


export type QueryFilesConnectionArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<FileOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<FileWhereInput>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type QueryPermissionsArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<PermissionOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<PermissionWhereInput>;
};


export type QueryPermissionsConnectionArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<PermissionOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<PermissionWhereInput>;
};


export type QueryRolesArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<RoleOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<RoleWhereInput>;
};


export type QueryRolesConnectionArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<RoleOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<RoleWhereInput>;
};


export type QueryUsersArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<UserOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<UserWhereInput>;
};


export type QueryUsersConnectionArgs = {
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<UserOrder>;
  skip?: InputMaybe<Scalars['Int']['input']>;
  where?: InputMaybe<UserWhereInput>;
};

export enum RelationType {
  Many = 'Many',
  ManyToMany = 'ManyToMany',
  ManyToOne = 'ManyToOne',
  One = 'One',
  OneToMany = 'OneToMany',
  OneToOne = 'OneToOne'
}

export type Role = Node & {
  __typename?: 'Role';
  adminCreatedBy?: Maybe<AdminUser>;
  adminUpdatedBy?: Maybe<AdminUser>;
  adminUserRoles?: Maybe<Array<AdminUser>>;
  createdAt?: Maybe<Scalars['Time']['output']>;
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  permissions?: Maybe<Array<Permission>>;
  updatedAt?: Maybe<Scalars['Time']['output']>;
  userRoles?: Maybe<Array<User>>;
};

/** A connection to a list of items. */
export type RoleConnection = {
  __typename?: 'RoleConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<RoleEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type RoleEdge = {
  __typename?: 'RoleEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Role>;
};

/** Ordering options for Role connections */
export type RoleOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Roles. */
  field: RoleOrderField;
};

/** Properties by which Role connections can be ordered. */
export enum RoleOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  Name = 'name',
  UpdatedAt = 'updatedAt'
}

/**
 * RoleWhereInput is used for filtering Role objects.
 * Input was generated by ent.
 */
export type RoleWhereInput = {
  and?: InputMaybe<Array<RoleWhereInput>>;
  /** created_at field predicates */
  createdAt?: InputMaybe<Scalars['Time']['input']>;
  createdAtGT?: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  createdAtLT?: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE?: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
  /** admin_created_by edge predicates */
  hasAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminCreatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_updated_by edge predicates */
  hasAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_user_roles edge predicates */
  hasAdminUserRoles?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUserRolesWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** permissions edge predicates */
  hasPermissions?: InputMaybe<Scalars['Boolean']['input']>;
  hasPermissionsWith?: InputMaybe<Array<PermissionWhereInput>>;
  /** user_roles edge predicates */
  hasUserRoles?: InputMaybe<Scalars['Boolean']['input']>;
  hasUserRolesWith?: InputMaybe<Array<UserWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idContainsFold?: InputMaybe<Scalars['ID']['input']>;
  idEqualFold?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<RoleWhereInput>;
  or?: InputMaybe<Array<RoleWhereInput>>;
  /** updated_at field predicates */
  updatedAt?: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT?: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE?: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  updatedAtLT?: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE?: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ?: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RoleWhereUniqueInput = {
  id?: InputMaybe<Scalars['ID']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type Subscription = {
  __typename?: 'Subscription';
  appStatus: AppStatus;
  entities?: Maybe<Array<Entity>>;
};

/**
 * UpdateAdminUserInput is used for update AdminUser object.
 * Input was generated by ent.
 */
export type UpdateAdminUserInput = {
  addRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  adminCreatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminUpdatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  clearDefaultRole?: InputMaybe<Scalars['Boolean']['input']>;
  clearName?: InputMaybe<Scalars['Boolean']['input']>;
  clearRoles?: InputMaybe<Scalars['Boolean']['input']>;
  defaultRole?: InputMaybe<UpdateOneRoleInput>;
  defaultRoleID?: InputMaybe<Scalars['ID']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  firstName?: InputMaybe<Scalars['String']['input']>;
  lastName?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  password?: InputMaybe<Scalars['String']['input']>;
  refAdminCreatedBy?: InputMaybe<UpdateManyAdminUserInput>;
  refAdminUpdatedBy?: InputMaybe<UpdateManyAdminUserInput>;
  removeRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  roles?: InputMaybe<UpdateManyRoleInput>;
};

export type UpdateEdgeInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  private?: InputMaybe<Scalars['Boolean']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateEntityInput = {
  caption?: InputMaybe<Scalars['String']['input']>;
  displayField?: InputMaybe<FieldWhereUniqueInput>;
  edges?: InputMaybe<UpdateManyEdgesInput>;
  fields?: InputMaybe<UpdateManyFieldsInput>;
};

export type UpdateFieldInput = {
  acceptedValues?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  caption?: InputMaybe<Scalars['String']['input']>;
  defaultValue?: InputMaybe<Scalars['String']['input']>;
  max?: InputMaybe<Scalars['String']['input']>;
  min?: InputMaybe<Scalars['String']['input']>;
  private?: InputMaybe<Scalars['Boolean']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
  unique?: InputMaybe<Scalars['Boolean']['input']>;
};

/**
 * UpdateFileInput is used for update File object.
 * Input was generated by ent.
 */
export type UpdateFileInput = {
  adminCreatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminCreatedByID?: InputMaybe<Scalars['ID']['input']>;
  adminUpdatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminUpdatedByID?: InputMaybe<Scalars['ID']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  clearAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  clearAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  clearCaption?: InputMaybe<Scalars['Boolean']['input']>;
  clearCreatedAt?: InputMaybe<Scalars['Boolean']['input']>;
  clearCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  clearUpdatedAt?: InputMaybe<Scalars['Boolean']['input']>;
  clearUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  createdBy?: InputMaybe<UpdateOneUserInput>;
  createdByID?: InputMaybe<Scalars['ID']['input']>;
  mimeType?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  size?: InputMaybe<Scalars['Int']['input']>;
  storageFileName?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
  updatedBy?: InputMaybe<UpdateOneUserInput>;
  updatedByID?: InputMaybe<Scalars['ID']['input']>;
};

export type UpdateManyAdminUserInput = {
  connect?: InputMaybe<Array<AdminUserWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateAdminUserInput>>;
  delete?: InputMaybe<Array<AdminUserWhereUniqueInput>>;
  disconnect?: InputMaybe<Array<AdminUserWhereUniqueInput>>;
};

export type UpdateManyEdgesInput = {
  create?: InputMaybe<Array<CreateEdgeInput>>;
  delete?: InputMaybe<Array<EdgeWhereUniqueInput>>;
  update?: InputMaybe<Array<UpdateOneEdgeInput>>;
};

export type UpdateManyFieldsInput = {
  create?: InputMaybe<Array<CreateFieldInput>>;
  delete?: InputMaybe<Array<FieldWhereUniqueInput>>;
  update?: InputMaybe<Array<UpdateOneFieldInput>>;
};

export type UpdateManyFileInput = {
  connect?: InputMaybe<Array<FileWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateFileInput>>;
  delete?: InputMaybe<Array<FileWhereUniqueInput>>;
  disconnect?: InputMaybe<Array<FileWhereUniqueInput>>;
};

export type UpdateManyPermissionInput = {
  connect?: InputMaybe<Array<PermissionWhereUniqueInput>>;
  create?: InputMaybe<Array<CreatePermissionInput>>;
  delete?: InputMaybe<Array<PermissionWhereUniqueInput>>;
  disconnect?: InputMaybe<Array<PermissionWhereUniqueInput>>;
};

export type UpdateManyRoleInput = {
  connect?: InputMaybe<Array<RoleWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateRoleInput>>;
  delete?: InputMaybe<Array<RoleWhereUniqueInput>>;
  disconnect?: InputMaybe<Array<RoleWhereUniqueInput>>;
};

export type UpdateManyUserInput = {
  connect?: InputMaybe<Array<UserWhereUniqueInput>>;
  create?: InputMaybe<Array<CreateUserInput>>;
  delete?: InputMaybe<Array<UserWhereUniqueInput>>;
  disconnect?: InputMaybe<Array<UserWhereUniqueInput>>;
};

export type UpdateOneAdminUserInput = {
  connect?: InputMaybe<AdminUserWhereUniqueInput>;
  create?: InputMaybe<CreateAdminUserInput>;
  delete?: InputMaybe<Scalars['Boolean']['input']>;
  unset?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateOneEdgeInput = {
  data: UpdateEdgeInput;
  where: EdgeWhereUniqueInput;
};

export type UpdateOneFieldInput = {
  data: UpdateFieldInput;
  where: FieldWhereUniqueInput;
};

export type UpdateOneFileInput = {
  connect?: InputMaybe<FileWhereUniqueInput>;
  create?: InputMaybe<CreateFileInput>;
  delete?: InputMaybe<Scalars['Boolean']['input']>;
  unset?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateOnePermissionInput = {
  connect?: InputMaybe<PermissionWhereUniqueInput>;
  create?: InputMaybe<CreatePermissionInput>;
  delete?: InputMaybe<Scalars['Boolean']['input']>;
  unset?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateOneRoleInput = {
  connect?: InputMaybe<RoleWhereUniqueInput>;
  create?: InputMaybe<CreateRoleInput>;
  delete?: InputMaybe<Scalars['Boolean']['input']>;
  unset?: InputMaybe<Scalars['Boolean']['input']>;
};

export type UpdateOneUserInput = {
  connect?: InputMaybe<UserWhereUniqueInput>;
  create?: InputMaybe<CreateUserInput>;
  delete?: InputMaybe<Scalars['Boolean']['input']>;
  unset?: InputMaybe<Scalars['Boolean']['input']>;
};

/**
 * UpdatePermissionInput is used for update Permission object.
 * Input was generated by ent.
 */
export type UpdatePermissionInput = {
  adminCreatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminCreatedByID?: InputMaybe<Scalars['ID']['input']>;
  adminUpdatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminUpdatedByID?: InputMaybe<Scalars['ID']['input']>;
  clearAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  clearAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  clearCreatedAt?: InputMaybe<Scalars['Boolean']['input']>;
  clearRole?: InputMaybe<Scalars['Boolean']['input']>;
  clearUpdatedAt?: InputMaybe<Scalars['Boolean']['input']>;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  entity?: InputMaybe<Scalars['String']['input']>;
  operation?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<UpdateOneRoleInput>;
  roleID?: InputMaybe<Scalars['ID']['input']>;
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
};

/**
 * UpdateRoleInput is used for update Role object.
 * Input was generated by ent.
 */
export type UpdateRoleInput = {
  addAdminUserRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  addPermissionIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  addUserRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  adminCreatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  adminUpdatedBy?: InputMaybe<UpdateOneAdminUserInput>;
  clearAdminUserRoles?: InputMaybe<Scalars['Boolean']['input']>;
  clearPermissions?: InputMaybe<Scalars['Boolean']['input']>;
  clearUserRoles?: InputMaybe<Scalars['Boolean']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  permissions?: InputMaybe<UpdateManyPermissionInput>;
  removeAdminUserRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  removePermissionIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  removeUserRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  userRoles?: InputMaybe<UpdateManyAdminUserInput>;
};

/**
 * UpdateUserInput is used for update User object.
 * Input was generated by ent.
 */
export type UpdateUserInput = {
  addRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  clearDefaultRole?: InputMaybe<Scalars['Boolean']['input']>;
  clearRoles?: InputMaybe<Scalars['Boolean']['input']>;
  createdBy?: InputMaybe<UpdateOneUserInput>;
  defaultRole?: InputMaybe<UpdateOneRoleInput>;
  defaultRoleID?: InputMaybe<Scalars['ID']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  password?: InputMaybe<Scalars['String']['input']>;
  refCreatedBy?: InputMaybe<UpdateManyUserInput>;
  refUpdatedBy?: InputMaybe<UpdateManyUserInput>;
  removeRoleIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  roles?: InputMaybe<UpdateManyRoleInput>;
  updatedBy?: InputMaybe<UpdateOneUserInput>;
};

export type User = Node & {
  __typename?: 'User';
  adminCreatedBy?: Maybe<AdminUser>;
  adminUpdatedBy?: Maybe<AdminUser>;
  createdBy?: Maybe<User>;
  defaultRole?: Maybe<Role>;
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  password: Scalars['String']['output'];
  roles?: Maybe<Array<Role>>;
  updatedBy?: Maybe<User>;
};

/** A connection to a list of items. */
export type UserConnection = {
  __typename?: 'UserConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<UserEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type UserEdge = {
  __typename?: 'UserEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<User>;
};

/** Ordering options for User connections */
export type UserOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Users. */
  field: UserOrderField;
};

/** Properties by which User connections can be ordered. */
export enum UserOrderField {
  Email = 'email',
  Id = 'id'
}

/**
 * UserWhereInput is used for filtering User objects.
 * Input was generated by ent.
 */
export type UserWhereInput = {
  and?: InputMaybe<Array<UserWhereInput>>;
  /** email field predicates */
  email?: InputMaybe<Scalars['String']['input']>;
  emailContains?: InputMaybe<Scalars['String']['input']>;
  emailContainsFold?: InputMaybe<Scalars['String']['input']>;
  emailEqualFold?: InputMaybe<Scalars['String']['input']>;
  emailGT?: InputMaybe<Scalars['String']['input']>;
  emailGTE?: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix?: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix?: InputMaybe<Scalars['String']['input']>;
  emailIn?: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT?: InputMaybe<Scalars['String']['input']>;
  emailLTE?: InputMaybe<Scalars['String']['input']>;
  emailNEQ?: InputMaybe<Scalars['String']['input']>;
  emailNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** admin_created_by edge predicates */
  hasAdminCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminCreatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** admin_updated_by edge predicates */
  hasAdminUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasAdminUpdatedByWith?: InputMaybe<Array<AdminUserWhereInput>>;
  /** created_by edge predicates */
  hasCreatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasCreatedByWith?: InputMaybe<Array<UserWhereInput>>;
  /** default_role edge predicates */
  hasDefaultRole?: InputMaybe<Scalars['Boolean']['input']>;
  hasDefaultRoleWith?: InputMaybe<Array<RoleWhereInput>>;
  /** roles edge predicates */
  hasRoles?: InputMaybe<Scalars['Boolean']['input']>;
  hasRolesWith?: InputMaybe<Array<RoleWhereInput>>;
  /** updated_by edge predicates */
  hasUpdatedBy?: InputMaybe<Scalars['Boolean']['input']>;
  hasUpdatedByWith?: InputMaybe<Array<UserWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idContainsFold?: InputMaybe<Scalars['ID']['input']>;
  idEqualFold?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<UserWhereInput>;
  or?: InputMaybe<Array<UserWhereInput>>;
  /** password field predicates */
  password?: InputMaybe<Scalars['String']['input']>;
  passwordContains?: InputMaybe<Scalars['String']['input']>;
  passwordContainsFold?: InputMaybe<Scalars['String']['input']>;
  passwordEqualFold?: InputMaybe<Scalars['String']['input']>;
  passwordGT?: InputMaybe<Scalars['String']['input']>;
  passwordGTE?: InputMaybe<Scalars['String']['input']>;
  passwordHasPrefix?: InputMaybe<Scalars['String']['input']>;
  passwordHasSuffix?: InputMaybe<Scalars['String']['input']>;
  passwordIn?: InputMaybe<Array<Scalars['String']['input']>>;
  passwordLT?: InputMaybe<Scalars['String']['input']>;
  passwordLTE?: InputMaybe<Scalars['String']['input']>;
  passwordNEQ?: InputMaybe<Scalars['String']['input']>;
  passwordNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
};

export type UserWhereUniqueInput = {
  email?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
};
