// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/migration"
	"app/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Migration is the model entity for the Migration schema.
type Migration struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type migration.Type `json:"type,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction migration.Direction `json:"direction,omitempty"`
	// Plugin holds the value of the "plugin" field.
	Plugin string `json:"plugin,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MigrationQuery when eager-loading is set.
	Edges                MigrationEdges `json:"edges"`
	migration_created_by *string
	migration_updated_by *string
	selectValues         sql.SelectValues
}

// MigrationEdges holds the relations/edges for other nodes in the graph.
type MigrationEdges struct {
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the updated_by edge.
	UpdatedBy *User `json:"updated_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MigrationEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// UpdatedByOrErr returns the UpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MigrationEdges) UpdatedByOrErr() (*User, error) {
	if e.UpdatedBy != nil {
		return e.UpdatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updated_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Migration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case migration.FieldID, migration.FieldName, migration.FieldType, migration.FieldDirection, migration.FieldPlugin:
			values[i] = new(sql.NullString)
		case migration.FieldCreatedAt, migration.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case migration.ForeignKeys[0]: // migration_created_by
			values[i] = new(sql.NullString)
		case migration.ForeignKeys[1]: // migration_updated_by
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Migration fields.
func (m *Migration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case migration.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				m.ID = value.String
			}
		case migration.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				m.Name = value.String
			}
		case migration.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				m.Type = migration.Type(value.String)
			}
		case migration.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				m.Direction = migration.Direction(value.String)
			}
		case migration.FieldPlugin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plugin", values[i])
			} else if value.Valid {
				m.Plugin = value.String
			}
		case migration.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				m.CreatedAt = new(time.Time)
				*m.CreatedAt = value.Time
			}
		case migration.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				m.UpdatedAt = new(time.Time)
				*m.UpdatedAt = value.Time
			}
		case migration.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field migration_created_by", values[i])
			} else if value.Valid {
				m.migration_created_by = new(string)
				*m.migration_created_by = value.String
			}
		case migration.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field migration_updated_by", values[i])
			} else if value.Valid {
				m.migration_updated_by = new(string)
				*m.migration_updated_by = value.String
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Migration.
// This includes values selected through modifiers, order, etc.
func (m *Migration) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryCreatedBy queries the "created_by" edge of the Migration entity.
func (m *Migration) QueryCreatedBy() *UserQuery {
	return NewMigrationClient(m.config).QueryCreatedBy(m)
}

// QueryUpdatedBy queries the "updated_by" edge of the Migration entity.
func (m *Migration) QueryUpdatedBy() *UserQuery {
	return NewMigrationClient(m.config).QueryUpdatedBy(m)
}

// Update returns a builder for updating this Migration.
// Note that you need to call Migration.Unwrap() before calling this method if this Migration
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Migration) Update() *MigrationUpdateOne {
	return NewMigrationClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Migration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Migration) Unwrap() *Migration {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Migration is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Migration) String() string {
	var builder strings.Builder
	builder.WriteString("Migration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("name=")
	builder.WriteString(m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", m.Type))
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(fmt.Sprintf("%v", m.Direction))
	builder.WriteString(", ")
	builder.WriteString("plugin=")
	builder.WriteString(m.Plugin)
	builder.WriteString(", ")
	if v := m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Migrations is a parsable slice of Migration.
type Migrations []*Migration
