// Code generated by internal template, DO NOT EDIT.

package ent

import (
	"app/ent/user"
	"fmt"
)

// AddEdges sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *MigrationMutation) AddEdges(name string, values []string) error {
	switch name {
	}
	return fmt.Errorf("unknown Migration edge %s", name)
}

// AddEdges sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *RoleMutation) AddEdges(name string, values []string) error {
	switch name {
	}
	return fmt.Errorf("unknown Role edge %s", name)
}

// AddEdges sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *UserMutation) AddEdges(name string, values []string) error {
	switch name {
	case user.EdgeRefCreatedBy:
		m.AddRefCreatedByIDs(values...)
		return nil
	case user.EdgeRefUpdatedBy:
		m.AddRefUpdatedByIDs(values...)
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
