// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRefreshToken is the predicate function for userrefreshtoken builders.
type UserRefreshToken func(*sql.Selector)
