// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/adminuser"
	"app/ent/forpermission"
	"app/ent/predicate"
	"app/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ForPermissionUpdate is the builder for updating ForPermission entities.
type ForPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *ForPermissionMutation
}

// Where appends a list predicates to the ForPermissionUpdate builder.
func (_u *ForPermissionUpdate) Where(ps ...predicate.ForPermission) *ForPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ForPermissionUpdate) SetCreatedAt(v time.Time) *ForPermissionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableCreatedAt(v *time.Time) *ForPermissionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ForPermissionUpdate) ClearCreatedAt() *ForPermissionUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ForPermissionUpdate) SetUpdatedAt(v time.Time) *ForPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ForPermissionUpdate) ClearUpdatedAt() *ForPermissionUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ForPermissionUpdate) SetName(v string) *ForPermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableName(v *string) *ForPermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ForPermissionUpdate) ClearName() *ForPermissionUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAge sets the "age" field.
func (_u *ForPermissionUpdate) SetAge(v int) *ForPermissionUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableAge(v *int) *ForPermissionUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *ForPermissionUpdate) AddAge(v int) *ForPermissionUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *ForPermissionUpdate) ClearAge() *ForPermissionUpdate {
	_u.mutation.ClearAge()
	return _u
}

// SetIsStupid sets the "is_stupid" field.
func (_u *ForPermissionUpdate) SetIsStupid(v bool) *ForPermissionUpdate {
	_u.mutation.SetIsStupid(v)
	return _u
}

// SetNillableIsStupid sets the "is_stupid" field if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableIsStupid(v *bool) *ForPermissionUpdate {
	if v != nil {
		_u.SetIsStupid(*v)
	}
	return _u
}

// ClearIsStupid clears the value of the "is_stupid" field.
func (_u *ForPermissionUpdate) ClearIsStupid() *ForPermissionUpdate {
	_u.mutation.ClearIsStupid()
	return _u
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *ForPermissionUpdate) SetCreatedByID(id string) *ForPermissionUpdate {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableCreatedByID(id *string) *ForPermissionUpdate {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *ForPermissionUpdate) SetCreatedBy(v *User) *ForPermissionUpdate {
	return _u.SetCreatedByID(v.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (_u *ForPermissionUpdate) SetUpdatedByID(id string) *ForPermissionUpdate {
	_u.mutation.SetUpdatedByID(id)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by" edge to the User entity by ID if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableUpdatedByID(id *string) *ForPermissionUpdate {
	if id != nil {
		_u = _u.SetUpdatedByID(*id)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (_u *ForPermissionUpdate) SetUpdatedBy(v *User) *ForPermissionUpdate {
	return _u.SetUpdatedByID(v.ID)
}

// SetAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID.
func (_u *ForPermissionUpdate) SetAdminCreatedByID(id string) *ForPermissionUpdate {
	_u.mutation.SetAdminCreatedByID(id)
	return _u
}

// SetNillableAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableAdminCreatedByID(id *string) *ForPermissionUpdate {
	if id != nil {
		_u = _u.SetAdminCreatedByID(*id)
	}
	return _u
}

// SetAdminCreatedBy sets the "admin_created_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdate) SetAdminCreatedBy(v *AdminUser) *ForPermissionUpdate {
	return _u.SetAdminCreatedByID(v.ID)
}

// SetAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID.
func (_u *ForPermissionUpdate) SetAdminUpdatedByID(id string) *ForPermissionUpdate {
	_u.mutation.SetAdminUpdatedByID(id)
	return _u
}

// SetNillableAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ForPermissionUpdate) SetNillableAdminUpdatedByID(id *string) *ForPermissionUpdate {
	if id != nil {
		_u = _u.SetAdminUpdatedByID(*id)
	}
	return _u
}

// SetAdminUpdatedBy sets the "admin_updated_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdate) SetAdminUpdatedBy(v *AdminUser) *ForPermissionUpdate {
	return _u.SetAdminUpdatedByID(v.ID)
}

// Mutation returns the ForPermissionMutation object of the builder.
func (_u *ForPermissionUpdate) Mutation() *ForPermissionMutation {
	return _u.mutation
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *ForPermissionUpdate) ClearCreatedBy() *ForPermissionUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// ClearUpdatedBy clears the "updated_by" edge to the User entity.
func (_u *ForPermissionUpdate) ClearUpdatedBy() *ForPermissionUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// ClearAdminCreatedBy clears the "admin_created_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdate) ClearAdminCreatedBy() *ForPermissionUpdate {
	_u.mutation.ClearAdminCreatedBy()
	return _u
}

// ClearAdminUpdatedBy clears the "admin_updated_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdate) ClearAdminUpdatedBy() *ForPermissionUpdate {
	_u.mutation.ClearAdminUpdatedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ForPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ForPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ForPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ForPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ForPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := forpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ForPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(forpermission.Table, forpermission.Columns, sqlgraph.NewFieldSpec(forpermission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(forpermission.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(forpermission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(forpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(forpermission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(forpermission.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(forpermission.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(forpermission.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(forpermission.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(forpermission.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.IsStupid(); ok {
		_spec.SetField(forpermission.FieldIsStupid, field.TypeBool, value)
	}
	if _u.mutation.IsStupidCleared() {
		_spec.ClearField(forpermission.FieldIsStupid, field.TypeBool)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.CreatedByTable,
			Columns: []string{forpermission.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.CreatedByTable,
			Columns: []string{forpermission.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.UpdatedByTable,
			Columns: []string{forpermission.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.UpdatedByTable,
			Columns: []string{forpermission.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminCreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminCreatedByTable,
			Columns: []string{forpermission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminCreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminCreatedByTable,
			Columns: []string{forpermission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminUpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminUpdatedByTable,
			Columns: []string{forpermission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminUpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminUpdatedByTable,
			Columns: []string{forpermission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{forpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ForPermissionUpdateOne is the builder for updating a single ForPermission entity.
type ForPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ForPermissionMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *ForPermissionUpdateOne) SetCreatedAt(v time.Time) *ForPermissionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableCreatedAt(v *time.Time) *ForPermissionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ForPermissionUpdateOne) ClearCreatedAt() *ForPermissionUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ForPermissionUpdateOne) SetUpdatedAt(v time.Time) *ForPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ForPermissionUpdateOne) ClearUpdatedAt() *ForPermissionUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ForPermissionUpdateOne) SetName(v string) *ForPermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableName(v *string) *ForPermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ForPermissionUpdateOne) ClearName() *ForPermissionUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAge sets the "age" field.
func (_u *ForPermissionUpdateOne) SetAge(v int) *ForPermissionUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableAge(v *int) *ForPermissionUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *ForPermissionUpdateOne) AddAge(v int) *ForPermissionUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *ForPermissionUpdateOne) ClearAge() *ForPermissionUpdateOne {
	_u.mutation.ClearAge()
	return _u
}

// SetIsStupid sets the "is_stupid" field.
func (_u *ForPermissionUpdateOne) SetIsStupid(v bool) *ForPermissionUpdateOne {
	_u.mutation.SetIsStupid(v)
	return _u
}

// SetNillableIsStupid sets the "is_stupid" field if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableIsStupid(v *bool) *ForPermissionUpdateOne {
	if v != nil {
		_u.SetIsStupid(*v)
	}
	return _u
}

// ClearIsStupid clears the value of the "is_stupid" field.
func (_u *ForPermissionUpdateOne) ClearIsStupid() *ForPermissionUpdateOne {
	_u.mutation.ClearIsStupid()
	return _u
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *ForPermissionUpdateOne) SetCreatedByID(id string) *ForPermissionUpdateOne {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableCreatedByID(id *string) *ForPermissionUpdateOne {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *ForPermissionUpdateOne) SetCreatedBy(v *User) *ForPermissionUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (_u *ForPermissionUpdateOne) SetUpdatedByID(id string) *ForPermissionUpdateOne {
	_u.mutation.SetUpdatedByID(id)
	return _u
}

// SetNillableUpdatedByID sets the "updated_by" edge to the User entity by ID if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableUpdatedByID(id *string) *ForPermissionUpdateOne {
	if id != nil {
		_u = _u.SetUpdatedByID(*id)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (_u *ForPermissionUpdateOne) SetUpdatedBy(v *User) *ForPermissionUpdateOne {
	return _u.SetUpdatedByID(v.ID)
}

// SetAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID.
func (_u *ForPermissionUpdateOne) SetAdminCreatedByID(id string) *ForPermissionUpdateOne {
	_u.mutation.SetAdminCreatedByID(id)
	return _u
}

// SetNillableAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableAdminCreatedByID(id *string) *ForPermissionUpdateOne {
	if id != nil {
		_u = _u.SetAdminCreatedByID(*id)
	}
	return _u
}

// SetAdminCreatedBy sets the "admin_created_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdateOne) SetAdminCreatedBy(v *AdminUser) *ForPermissionUpdateOne {
	return _u.SetAdminCreatedByID(v.ID)
}

// SetAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID.
func (_u *ForPermissionUpdateOne) SetAdminUpdatedByID(id string) *ForPermissionUpdateOne {
	_u.mutation.SetAdminUpdatedByID(id)
	return _u
}

// SetNillableAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ForPermissionUpdateOne) SetNillableAdminUpdatedByID(id *string) *ForPermissionUpdateOne {
	if id != nil {
		_u = _u.SetAdminUpdatedByID(*id)
	}
	return _u
}

// SetAdminUpdatedBy sets the "admin_updated_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdateOne) SetAdminUpdatedBy(v *AdminUser) *ForPermissionUpdateOne {
	return _u.SetAdminUpdatedByID(v.ID)
}

// Mutation returns the ForPermissionMutation object of the builder.
func (_u *ForPermissionUpdateOne) Mutation() *ForPermissionMutation {
	return _u.mutation
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *ForPermissionUpdateOne) ClearCreatedBy() *ForPermissionUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// ClearUpdatedBy clears the "updated_by" edge to the User entity.
func (_u *ForPermissionUpdateOne) ClearUpdatedBy() *ForPermissionUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// ClearAdminCreatedBy clears the "admin_created_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdateOne) ClearAdminCreatedBy() *ForPermissionUpdateOne {
	_u.mutation.ClearAdminCreatedBy()
	return _u
}

// ClearAdminUpdatedBy clears the "admin_updated_by" edge to the AdminUser entity.
func (_u *ForPermissionUpdateOne) ClearAdminUpdatedBy() *ForPermissionUpdateOne {
	_u.mutation.ClearAdminUpdatedBy()
	return _u
}

// Where appends a list predicates to the ForPermissionUpdate builder.
func (_u *ForPermissionUpdateOne) Where(ps ...predicate.ForPermission) *ForPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ForPermissionUpdateOne) Select(field string, fields ...string) *ForPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ForPermission entity.
func (_u *ForPermissionUpdateOne) Save(ctx context.Context) (*ForPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ForPermissionUpdateOne) SaveX(ctx context.Context) *ForPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ForPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ForPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ForPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := forpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ForPermissionUpdateOne) sqlSave(ctx context.Context) (_node *ForPermission, err error) {
	_spec := sqlgraph.NewUpdateSpec(forpermission.Table, forpermission.Columns, sqlgraph.NewFieldSpec(forpermission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ForPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, forpermission.FieldID)
		for _, f := range fields {
			if !forpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != forpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(forpermission.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(forpermission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(forpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(forpermission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(forpermission.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(forpermission.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(forpermission.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(forpermission.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(forpermission.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.IsStupid(); ok {
		_spec.SetField(forpermission.FieldIsStupid, field.TypeBool, value)
	}
	if _u.mutation.IsStupidCleared() {
		_spec.ClearField(forpermission.FieldIsStupid, field.TypeBool)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.CreatedByTable,
			Columns: []string{forpermission.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.CreatedByTable,
			Columns: []string{forpermission.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.UpdatedByTable,
			Columns: []string{forpermission.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.UpdatedByTable,
			Columns: []string{forpermission.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminCreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminCreatedByTable,
			Columns: []string{forpermission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminCreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminCreatedByTable,
			Columns: []string{forpermission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminUpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminUpdatedByTable,
			Columns: []string{forpermission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminUpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   forpermission.AdminUpdatedByTable,
			Columns: []string{forpermission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ForPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{forpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
