// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/adminuser"
	"app/ent/miau"
	"app/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Miau is the model entity for the Miau schema.
type Miau struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MiauQuery when eager-loading is set.
	Edges                 MiauEdges `json:"edges"`
	miau_created_by       *string
	miau_updated_by       *string
	miau_admin_created_by *string
	miau_admin_updated_by *string
	selectValues          sql.SelectValues
}

// MiauEdges holds the relations/edges for other nodes in the graph.
type MiauEdges struct {
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the updated_by edge.
	UpdatedBy *User `json:"updated_by,omitempty"`
	// AdminCreatedBy holds the value of the admin_created_by edge.
	AdminCreatedBy *AdminUser `json:"admin_created_by,omitempty"`
	// AdminUpdatedBy holds the value of the admin_updated_by edge.
	AdminUpdatedBy *AdminUser `json:"admin_updated_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [4]map[string]int
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MiauEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// UpdatedByOrErr returns the UpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MiauEdges) UpdatedByOrErr() (*User, error) {
	if e.UpdatedBy != nil {
		return e.UpdatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updated_by"}
}

// AdminCreatedByOrErr returns the AdminCreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MiauEdges) AdminCreatedByOrErr() (*AdminUser, error) {
	if e.AdminCreatedBy != nil {
		return e.AdminCreatedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "admin_created_by"}
}

// AdminUpdatedByOrErr returns the AdminUpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MiauEdges) AdminUpdatedByOrErr() (*AdminUser, error) {
	if e.AdminUpdatedBy != nil {
		return e.AdminUpdatedBy, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "admin_updated_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Miau) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case miau.FieldID, miau.FieldName:
			values[i] = new(sql.NullString)
		case miau.FieldCreatedAt, miau.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case miau.ForeignKeys[0]: // miau_created_by
			values[i] = new(sql.NullString)
		case miau.ForeignKeys[1]: // miau_updated_by
			values[i] = new(sql.NullString)
		case miau.ForeignKeys[2]: // miau_admin_created_by
			values[i] = new(sql.NullString)
		case miau.ForeignKeys[3]: // miau_admin_updated_by
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Miau fields.
func (_m *Miau) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case miau.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case miau.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case miau.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case miau.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case miau.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field miau_created_by", values[i])
			} else if value.Valid {
				_m.miau_created_by = new(string)
				*_m.miau_created_by = value.String
			}
		case miau.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field miau_updated_by", values[i])
			} else if value.Valid {
				_m.miau_updated_by = new(string)
				*_m.miau_updated_by = value.String
			}
		case miau.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field miau_admin_created_by", values[i])
			} else if value.Valid {
				_m.miau_admin_created_by = new(string)
				*_m.miau_admin_created_by = value.String
			}
		case miau.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field miau_admin_updated_by", values[i])
			} else if value.Valid {
				_m.miau_admin_updated_by = new(string)
				*_m.miau_admin_updated_by = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Miau.
// This includes values selected through modifiers, order, etc.
func (_m *Miau) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreatedBy queries the "created_by" edge of the Miau entity.
func (_m *Miau) QueryCreatedBy() *UserQuery {
	return NewMiauClient(_m.config).QueryCreatedBy(_m)
}

// QueryUpdatedBy queries the "updated_by" edge of the Miau entity.
func (_m *Miau) QueryUpdatedBy() *UserQuery {
	return NewMiauClient(_m.config).QueryUpdatedBy(_m)
}

// QueryAdminCreatedBy queries the "admin_created_by" edge of the Miau entity.
func (_m *Miau) QueryAdminCreatedBy() *AdminUserQuery {
	return NewMiauClient(_m.config).QueryAdminCreatedBy(_m)
}

// QueryAdminUpdatedBy queries the "admin_updated_by" edge of the Miau entity.
func (_m *Miau) QueryAdminUpdatedBy() *AdminUserQuery {
	return NewMiauClient(_m.config).QueryAdminUpdatedBy(_m)
}

// Update returns a builder for updating this Miau.
// Note that you need to call Miau.Unwrap() before calling this method if this Miau
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Miau) Update() *MiauUpdateOne {
	return NewMiauClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Miau entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Miau) Unwrap() *Miau {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Miau is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Miau) String() string {
	var builder strings.Builder
	builder.WriteString("Miau(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Miaus is a parsable slice of Miau.
type Miaus []*Miau
