// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/adminuser"
	"app/ent/miau"
	"app/ent/predicate"
	"app/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MiauQuery is the builder for querying Miau entities.
type MiauQuery struct {
	config
	ctx                *QueryContext
	order              []miau.OrderOption
	inters             []Interceptor
	predicates         []predicate.Miau
	withCreatedBy      *UserQuery
	withUpdatedBy      *UserQuery
	withAdminCreatedBy *AdminUserQuery
	withAdminUpdatedBy *AdminUserQuery
	withFKs            bool
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Miau) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiauQuery builder.
func (_q *MiauQuery) Where(ps ...predicate.Miau) *MiauQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MiauQuery) Limit(limit int) *MiauQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MiauQuery) Offset(offset int) *MiauQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MiauQuery) Unique(unique bool) *MiauQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MiauQuery) Order(o ...miau.OrderOption) *MiauQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCreatedBy chains the current query on the "created_by" edge.
func (_q *MiauQuery) QueryCreatedBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(miau.Table, miau.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, miau.CreatedByTable, miau.CreatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdatedBy chains the current query on the "updated_by" edge.
func (_q *MiauQuery) QueryUpdatedBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(miau.Table, miau.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, miau.UpdatedByTable, miau.UpdatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdminCreatedBy chains the current query on the "admin_created_by" edge.
func (_q *MiauQuery) QueryAdminCreatedBy() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(miau.Table, miau.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, miau.AdminCreatedByTable, miau.AdminCreatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdminUpdatedBy chains the current query on the "admin_updated_by" edge.
func (_q *MiauQuery) QueryAdminUpdatedBy() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(miau.Table, miau.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, miau.AdminUpdatedByTable, miau.AdminUpdatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Miau entity from the query.
// Returns a *NotFoundError when no Miau was found.
func (_q *MiauQuery) First(ctx context.Context) (*Miau, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{miau.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MiauQuery) FirstX(ctx context.Context) *Miau {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Miau ID from the query.
// Returns a *NotFoundError when no Miau ID was found.
func (_q *MiauQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{miau.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MiauQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Miau entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Miau entity is found.
// Returns a *NotFoundError when no Miau entities are found.
func (_q *MiauQuery) Only(ctx context.Context) (*Miau, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{miau.Label}
	default:
		return nil, &NotSingularError{miau.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MiauQuery) OnlyX(ctx context.Context) *Miau {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Miau ID in the query.
// Returns a *NotSingularError when more than one Miau ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MiauQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{miau.Label}
	default:
		err = &NotSingularError{miau.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MiauQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Miaus.
func (_q *MiauQuery) All(ctx context.Context) ([]*Miau, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Miau, *MiauQuery]()
	return withInterceptors[[]*Miau](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MiauQuery) AllX(ctx context.Context) []*Miau {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Miau IDs.
func (_q *MiauQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(miau.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MiauQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MiauQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MiauQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MiauQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MiauQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MiauQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiauQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MiauQuery) Clone() *MiauQuery {
	if _q == nil {
		return nil
	}
	return &MiauQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]miau.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.Miau{}, _q.predicates...),
		withCreatedBy:      _q.withCreatedBy.Clone(),
		withUpdatedBy:      _q.withUpdatedBy.Clone(),
		withAdminCreatedBy: _q.withAdminCreatedBy.Clone(),
		withAdminUpdatedBy: _q.withAdminUpdatedBy.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCreatedBy tells the query-builder to eager-load the nodes that are connected to
// the "created_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MiauQuery) WithCreatedBy(opts ...func(*UserQuery)) *MiauQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreatedBy = query
	return _q
}

// WithUpdatedBy tells the query-builder to eager-load the nodes that are connected to
// the "updated_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MiauQuery) WithUpdatedBy(opts ...func(*UserQuery)) *MiauQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUpdatedBy = query
	return _q
}

// WithAdminCreatedBy tells the query-builder to eager-load the nodes that are connected to
// the "admin_created_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MiauQuery) WithAdminCreatedBy(opts ...func(*AdminUserQuery)) *MiauQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdminCreatedBy = query
	return _q
}

// WithAdminUpdatedBy tells the query-builder to eager-load the nodes that are connected to
// the "admin_updated_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MiauQuery) WithAdminUpdatedBy(opts ...func(*AdminUserQuery)) *MiauQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdminUpdatedBy = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Miau.Query().
//		GroupBy(miau.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MiauQuery) GroupBy(field string, fields ...string) *MiauGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MiauGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = miau.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Miau.Query().
//		Select(miau.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *MiauQuery) Select(fields ...string) *MiauSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MiauSelect{MiauQuery: _q}
	sbuild.label = miau.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MiauSelect configured with the given aggregations.
func (_q *MiauQuery) Aggregate(fns ...AggregateFunc) *MiauSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MiauQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !miau.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MiauQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Miau, error) {
	var (
		nodes       = []*Miau{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withCreatedBy != nil,
			_q.withUpdatedBy != nil,
			_q.withAdminCreatedBy != nil,
			_q.withAdminUpdatedBy != nil,
		}
	)
	if _q.withCreatedBy != nil || _q.withUpdatedBy != nil || _q.withAdminCreatedBy != nil || _q.withAdminUpdatedBy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, miau.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Miau).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Miau{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCreatedBy; query != nil {
		if err := _q.loadCreatedBy(ctx, query, nodes, nil,
			func(n *Miau, e *User) { n.Edges.CreatedBy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUpdatedBy; query != nil {
		if err := _q.loadUpdatedBy(ctx, query, nodes, nil,
			func(n *Miau, e *User) { n.Edges.UpdatedBy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdminCreatedBy; query != nil {
		if err := _q.loadAdminCreatedBy(ctx, query, nodes, nil,
			func(n *Miau, e *AdminUser) { n.Edges.AdminCreatedBy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdminUpdatedBy; query != nil {
		if err := _q.loadAdminUpdatedBy(ctx, query, nodes, nil,
			func(n *Miau, e *AdminUser) { n.Edges.AdminUpdatedBy = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MiauQuery) loadCreatedBy(ctx context.Context, query *UserQuery, nodes []*Miau, init func(*Miau), assign func(*Miau, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Miau)
	for i := range nodes {
		if nodes[i].miau_created_by == nil {
			continue
		}
		fk := *nodes[i].miau_created_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "miau_created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MiauQuery) loadUpdatedBy(ctx context.Context, query *UserQuery, nodes []*Miau, init func(*Miau), assign func(*Miau, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Miau)
	for i := range nodes {
		if nodes[i].miau_updated_by == nil {
			continue
		}
		fk := *nodes[i].miau_updated_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "miau_updated_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MiauQuery) loadAdminCreatedBy(ctx context.Context, query *AdminUserQuery, nodes []*Miau, init func(*Miau), assign func(*Miau, *AdminUser)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Miau)
	for i := range nodes {
		if nodes[i].miau_admin_created_by == nil {
			continue
		}
		fk := *nodes[i].miau_admin_created_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "miau_admin_created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *MiauQuery) loadAdminUpdatedBy(ctx context.Context, query *AdminUserQuery, nodes []*Miau, init func(*Miau), assign func(*Miau, *AdminUser)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Miau)
	for i := range nodes {
		if nodes[i].miau_admin_updated_by == nil {
			continue
		}
		fk := *nodes[i].miau_admin_updated_by
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "miau_admin_updated_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MiauQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MiauQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(miau.Table, miau.Columns, sqlgraph.NewFieldSpec(miau.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, miau.FieldID)
		for i := range fields {
			if fields[i] != miau.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MiauQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(miau.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = miau.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MiauGroupBy is the group-by builder for Miau entities.
type MiauGroupBy struct {
	selector
	build *MiauQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MiauGroupBy) Aggregate(fns ...AggregateFunc) *MiauGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MiauGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MiauQuery, *MiauGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MiauGroupBy) sqlScan(ctx context.Context, root *MiauQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MiauSelect is the builder for selecting fields of Miau entities.
type MiauSelect struct {
	*MiauQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MiauSelect) Aggregate(fns ...AggregateFunc) *MiauSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MiauSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MiauQuery, *MiauSelect](ctx, _s.MiauQuery, _s, _s.inters, v)
}

func (_s *MiauSelect) sqlScan(ctx context.Context, root *MiauQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
