package hooks

import (
	"context"
	"fmt"
	"reflect"

	"entgo.io/ent/dialect/sql"
	"github.com/GoLabra/labra/cache"
	"github.com/GoLabra/labra/constants"
	"github.com/GoLabra/labra/entgql/domain/svc"
	"github.com/GoLabra/labra/entgql/ent"
	"github.com/GoLabra/labra/entgql/entity"
	"github.com/GoLabra/labra/strcase"
)

// QueryWithAdminCreatedBy is an interface for queries that support owner filtering.
// The WhereAdminCreatedBy method is generated by the ent template system.
type QueryWithAdminCreatedBy interface {
	ent.Query
	WhereAdminCreatedBy(adminUserID string) ent.Query
}

// LifecycleFilterQuery is an interface for queries that support filtering by entity_state.
// The WhereEntityStateIn method is generated for entities with lifecycle enabled.
type LifecycleFilterQuery interface {
	ent.Query
	WhereEntityStateIn(states ...entity.EntityState) ent.Query
}

// LifecycleFilterMutation is an interface for mutations that support restricting by entity_state.
// The WhereEntityStateIn method is generated for entities with lifecycle enabled (UpdateMany/DeleteMany).
type LifecycleFilterMutation interface {
	WhereEntityStateIn(states ...entity.EntityState)
}

// LifecycleMutationTargetsChecker is implemented by lifecycle-entity mutations for UpdateOne/DeleteOne.
// permissionLifecycleAccess is one slice of allowed states per permission; empty slice means full access.
type LifecycleMutationTargetsChecker interface {
	TargetsAllowedByLifecycle(ctx context.Context) (*entity.EntityState, error)
}

// applyOwnerFilter applies the owner filter to any query that implements WhereAdminCreatedBy.
// This uses the generated WhereAdminCreatedBy method from the ent template.
func applyOwnerFilter(q ent.Query, adminUserID string) {
	if ownerQuery, ok := q.(QueryWithAdminCreatedBy); ok {
		ownerQuery.WhereAdminCreatedBy(adminUserID)
	}
}

type WherePred func(*sql.Selector)

// applyLifecycleFilter restricts the query to rows whose entity_state is in the allowed set.
func applyLifecycleFilter(q ent.Query, allowedStates []entity.EntityState) {
	if len(allowedStates) == 0 {
		return
	}
	if lq, ok := q.(LifecycleFilterQuery); ok {
		lq.WhereEntityStateIn(allowedStates...)
	}
}

// applyLifecycleFilterToMutation restricts the mutation to rows whose entity_state is in the allowed set.
// Used for UpdateMany/DeleteMany so only allowed rows are affected.
func applyLifecycleFilterToMutation(m ent.Mutation, allowedStates []entity.EntityState) {
	if len(allowedStates) == 0 {
		return
	}
	if lm, ok := m.(LifecycleFilterMutation); ok {
		lm.WhereEntityStateIn(allowedStates...)
	}
}

// allowedStatesFromPermissions returns the union of states allowed by the given permissions.
// Empty LifecycleAccess means all states. Returns nil when the union is all states (no filter needed).
func allowedStatesFromPermissions(permissions []*ent.Permission) []entity.EntityState {
	set := make(map[entity.EntityState]struct{})
	for _, perm := range permissions {
		if len(perm.LifecycleAccess) == 0 {
			return nil // full access
		}
		for _, s := range perm.LifecycleAccess {
			set[entity.EntityState(s)] = struct{}{}
		}
	}
	if len(set) == 3 {
		return nil
	}
	out := make([]entity.EntityState, 0, len(set))
	for st := range set {
		out = append(out, st)
	}
	return out
}

// CreatedByUpdatedByHook automatically sets created_by and updated_by fields
func CreatedByUpdatedByHook(next ent.Mutator) ent.Mutator {
	return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
		user, ok := ctx.Value(constants.UserContextValue).(*ent.User) // USER
		if ok {
			if m.Op().Is(ent.OpCreate) {
				if ml, ok := m.(interface{ SetCreatedByID(string) }); ok {
					ml.SetCreatedByID(user.ID)
				}
			} else if m.Op().Is(ent.OpUpdateOne) || m.Op().Is(ent.OpUpdate) {
				if ml, ok := m.(interface{ SetUpdatedByID(string) }); ok {
					ml.SetUpdatedByID(user.ID)
				}
			}
		}

		adminUser, ok := ctx.Value(constants.UserContextValue).(*ent.AdminUser) // ADMIN USER
		if ok {
			if m.Op().Is(ent.OpCreate) {
				if ml, ok := m.(interface{ SetAdminCreatedByID(string) }); ok {
					ml.SetAdminCreatedByID(adminUser.ID)
				}
			} else if m.Op().Is(ent.OpUpdateOne) || m.Op().Is(ent.OpUpdate) {
				if ml, ok := m.(interface{ SetAdminUpdatedByID(string) }); ok {
					ml.SetAdminUpdatedByID(adminUser.ID)
				}
			}
		}

		return next.Mutate(ctx, m)
	})
}

// EntityMutatePermission checks if the current user has permission to perform mutation operations
// This hook is applied to external API requests (GraphQL/REST) where isInternalOperationContextValue is not set
func EntityMutatePermission(next ent.Mutator) ent.Mutator {
	return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
		// Skip permission checks for internal operations
		if ctx.Value(constants.IsInternalOperationContextValue) == true {
			return next.Mutate(ctx, m)
		}

		t := m.Type()

		service, ok := ctx.Value(constants.AdminServiceContextValue).(*svc.Service)
		if !ok {
			return nil, fmt.Errorf("%s", svc.ErrServiceNotSetInContext)
		}

		role, ok := ctx.Value(constants.RoleContextValue).(*ent.Role)
		if !ok {
			return nil, fmt.Errorf("role not found in context")
		}

		if role.Name == string(constants.SuperAdmin) {
			return next.Mutate(ctx, m)
		}

		entityName := strcase.NodeNameToGraphqlName(t)

		var operationName string
		switch m.Op() {
		case ent.OpCreate:
			operationName = "Create"
		case ent.OpUpdate, ent.OpUpdateOne:
			operationName = "Update"
		case ent.OpDelete, ent.OpDeleteOne:
			operationName = "Delete"
		default:
			return nil, fmt.Errorf("unknown operation")
		}

		// Use internal context for permission queries (bypasses permission checks)
		iCtx := context.WithValue(ctx, constants.IsInternalOperationContextValue, true)
		permissions, err := service.Permission.Get(iCtx, &ent.PermissionWhereInput{
			HasRoleWith: []*ent.RoleWhereInput{
				{
					Name: &role.Name,
				},
			},
			Entity:      &entityName,
			OperationIn: []string{operationName, "Owner"},
		}, nil, nil, nil, nil)

		if err != nil || len(permissions) == 0 {
			return nil, fmt.Errorf("Forbidden: user lacks permissions for entity %s", entityName)
		}

		// For UpdateOne/DeleteOne: ensure each target row's state is allowed (check and reject).
		if m.Op().Is(ent.OpUpdateOne | ent.OpDeleteOne) {
			if checker, ok := m.(LifecycleMutationTargetsChecker); ok {
				lifecycleAccess := make(map[string]struct{})
				for _, p := range permissions {
					for _, s := range p.LifecycleAccess {
						lifecycleAccess[s] = struct{}{}
					}
				}

				entityState, err := checker.TargetsAllowedByLifecycle(ctx)
				if err != nil {
					return nil, fmt.Errorf("entity state check: %w", err)
				}
				if entityState != nil {
					if _, ok := lifecycleAccess[string(*entityState)]; !ok {
						return nil, fmt.Errorf("Forbidden: you may not update or delete this %s in its current lifecycle state", entityName)
					}
				}
			}
		}

		// For UpdateMany/DeleteMany: add lifecycle condition to the mutation (only allowed rows are affected).
		if m.Op().Is(ent.OpUpdate | ent.OpDelete) {
			if cachedEntity, ok := cache.Entity.Get(entityName); ok && cachedEntity.EntityState.Enabled {
				allowedStates := allowedStatesFromPermissions(permissions)
				applyLifecycleFilterToMutation(m, allowedStates)
			}
		}

		return next.Mutate(ctx, m)
	})
}

// EntityReadPermission creates an interceptor for read operations
// This interceptor is applied to external API requests (GraphQL/REST) where isInternalOperationContextValue is not set
func EntityReadPermission() ent.Interceptor {
	return ent.InterceptFunc(func(next ent.Querier) ent.Querier {
		return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
			// Skip permission checks for internal operations
			if ctx.Value(constants.IsInternalOperationContextValue) == true {
				return next.Query(ctx, q)
			}

			// Get entity name from the query type
			entityName := getEntityNameFromQuery(q)

			service, ok := ctx.Value(constants.AdminServiceContextValue).(*svc.Service)
			if !ok {
				return nil, fmt.Errorf("service not found in context")
			}

			role, ok := ctx.Value(constants.RoleContextValue).(*ent.Role)
			if !ok {
				return nil, fmt.Errorf("role not found in context")
			}

			if role.Name == string(constants.SuperAdmin) {
				return next.Query(ctx, q)
			}

			operationName := "Read"
			iCtx := context.WithValue(ctx, constants.IsInternalOperationContextValue, true)
			readPerms, err := service.Permission.Get(iCtx, &ent.PermissionWhereInput{
				HasRoleWith: []*ent.RoleWhereInput{{Name: &role.Name}},
				Entity:      &entityName,
				Operation:   &operationName,
			}, nil, nil, nil, nil)
			if err != nil {
				return nil, fmt.Errorf("Forbidden: user lacks permissions for entity %s", entityName)
			}

			ownerOperation := "Owner"
			ownerPerms, err := service.Permission.Get(iCtx, &ent.PermissionWhereInput{
				HasRoleWith: []*ent.RoleWhereInput{{Name: &role.Name}},
				Entity:      &entityName,
				Operation:   &ownerOperation,
			}, nil, nil, nil, nil)
			if err != nil {
				return nil, fmt.Errorf("Forbidden: user lacks permissions for entity %s", entityName)
			}

			allowedByRead := len(readPerms) > 0
			allowedByOwner := len(ownerPerms) > 0
			if !allowedByRead && !allowedByOwner {
				return nil, fmt.Errorf("Forbidden: user lacks permissions for entity %s", entityName)
			}

			// Collect all permissions that grant access for lifecycle_access union
			allPerms := make([]*ent.Permission, 0, len(readPerms)+len(ownerPerms))
			if allowedByRead {
				allPerms = append(allPerms, readPerms...)
			}
			if allowedByOwner {
				allPerms = append(allPerms, ownerPerms...)
			}
			allowedStates := allowedStatesFromPermissions(allPerms)
			if cachedEntity, ok := cache.Entity.Get(entityName); ok && cachedEntity.EntityState.Enabled && len(allowedStates) > 0 {
				applyLifecycleFilter(q, allowedStates)
			}

			if allowedByOwner && !allowedByRead {
				adminUser, ok := ctx.Value(constants.UserContextValue).(*ent.AdminUser)
				if !ok || adminUser == nil {
					return nil, fmt.Errorf("Forbidden: user lacks permissions for entity %s", entityName)
				}
				applyOwnerFilter(q, adminUser.ID)
			}

			return next.Query(ctx, q)
		})
	})
}

// getEntityNameFromQuery extracts the entity name from a query
func getEntityNameFromQuery(q ent.Query) string {
	// Use reflection to get the concrete type name
	t := reflect.TypeOf(q)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	// Remove "Query" suffix to get entity name
	entityName := t.Name()
	if len(entityName) > 5 && entityName[len(entityName)-5:] == "Query" {
		entityName = entityName[:len(entityName)-5]
	}

	return strcase.LowerFirstLetter(entityName)
}
