package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/GoLabra/labra/constants"
	"github.com/GoLabra/labra/entgql/ent"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.AdminUser, error) {
	user, ok := ctx.Value(constants.UserContextValue).(*ent.AdminUser)
	if !ok || user == nil {
		return nil, fmt.Errorf("unauthorized: no authenticated admin user found")
	}
	return user, nil
}
