package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/GoLabra/labra/entgql/ent"
	gqlgen "github.com/GoLabra/labra/entgql/generated"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Query returns gqlgen.QueryResolver implementation.
func (r *Resolver) Query() gqlgen.QueryResolver { return &queryResolver{r} }

// CreateRoleInput returns gqlgen.CreateRoleInputResolver implementation.
func (r *Resolver) CreateRoleInput() gqlgen.CreateRoleInputResolver {
	return &createRoleInputResolver{r}
}

// UpdateRoleInput returns gqlgen.UpdateRoleInputResolver implementation.
func (r *Resolver) UpdateRoleInput() gqlgen.UpdateRoleInputResolver {
	return &updateRoleInputResolver{r}
}

type queryResolver struct{ *Resolver }
type createRoleInputResolver struct{ *Resolver }
type updateRoleInputResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *createRoleInputResolver) AdminUserRoleIDs(ctx context.Context, obj *ent.CreateRoleInput, data []string) error {
	panic(fmt.Errorf("not implemented: AdminUserRoleIDs - adminUserRoleIDs"))
}
func (r *updateRoleInputResolver) AddAdminUserRoleIDs(ctx context.Context, obj *ent.UpdateRoleInput, data []string) error {
	panic(fmt.Errorf("not implemented: AddAdminUserRoleIDs - addAdminUserRoleIDs"))
}
func (r *updateRoleInputResolver) RemoveAdminUserRoleIDs(ctx context.Context, obj *ent.UpdateRoleInput, data []string) error {
	panic(fmt.Errorf("not implemented: RemoveAdminUserRoleIDs - removeAdminUserRoleIDs"))
}
func (r *updateRoleInputResolver) ClearAdminUserRoles(ctx context.Context, obj *ent.UpdateRoleInput, data *bool) error {
	panic(fmt.Errorf("not implemented: ClearAdminUserRoles - clearAdminUserRoles"))
}
*/
