package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	gqlgen "github.com/GoLabra/labra/entgql/generated"
	"github.com/GoLabra/labra/tokenrevocation"
)

// CleanupExpiredTokens is the resolver for the cleanupExpiredTokens field.
func (r *mutationResolver) CleanupExpiredTokens(ctx context.Context) (*gqlgen.CleanupExpiredTokensPayload, error) {
	client, iCtx, err := cronDB(ctx)
	if err != nil {
		return nil, err
	}

	affected, err := tokenrevocation.CleanupExpiredRevocations(iCtx, client, client.DialectName(), time.Now().UTC())
	if err != nil {
		return nil, err
	}

	return &gqlgen.CleanupExpiredTokensPayload{Count: int(affected)}, nil
}
