// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoLabra/labra/entgql/ent/adminrefreshtoken"
	"github.com/GoLabra/labra/entgql/ent/predicate"
)

// AdminRefreshTokenDelete is the builder for deleting a AdminRefreshToken entity.
type AdminRefreshTokenDelete struct {
	config
	hooks    []Hook
	mutation *AdminRefreshTokenMutation
}

// Where appends a list predicates to the AdminRefreshTokenDelete builder.
func (_d *AdminRefreshTokenDelete) Where(ps ...predicate.AdminRefreshToken) *AdminRefreshTokenDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminRefreshTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminRefreshTokenDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminRefreshTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminrefreshtoken.Table, sqlgraph.NewFieldSpec(adminrefreshtoken.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminRefreshTokenDeleteOne is the builder for deleting a single AdminRefreshToken entity.
type AdminRefreshTokenDeleteOne struct {
	_d *AdminRefreshTokenDelete
}

// Where appends a list predicates to the AdminRefreshTokenDelete builder.
func (_d *AdminRefreshTokenDeleteOne) Where(ps ...predicate.AdminRefreshToken) *AdminRefreshTokenDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminRefreshTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminrefreshtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminRefreshTokenDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
