// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoLabra/labra/entgql/ent/adminrefreshtoken"
	"github.com/GoLabra/labra/entgql/ent/adminuser"
)

// AdminRefreshToken is the model entity for the AdminRefreshToken schema.
type AdminRefreshToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminRefreshTokenQuery when eager-loading is set.
	Edges                     AdminRefreshTokenEdges `json:"edges"`
	admin_user_refresh_tokens *string
	selectValues              sql.SelectValues
}

// AdminRefreshTokenEdges holds the relations/edges for other nodes in the graph.
type AdminRefreshTokenEdges struct {
	// AdminUser holds the value of the admin_user edge.
	AdminUser *AdminUser `json:"admin_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// AdminUserOrErr returns the AdminUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminRefreshTokenEdges) AdminUserOrErr() (*AdminUser, error) {
	if e.AdminUser != nil {
		return e.AdminUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "admin_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminRefreshToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminrefreshtoken.FieldID, adminrefreshtoken.FieldTokenHash:
			values[i] = new(sql.NullString)
		case adminrefreshtoken.FieldExpiresAt, adminrefreshtoken.FieldUsedAt, adminrefreshtoken.FieldRevokedAt, adminrefreshtoken.FieldCreatedAt, adminrefreshtoken.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case adminrefreshtoken.ForeignKeys[0]: // admin_user_refresh_tokens
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminRefreshToken fields.
func (_m *AdminRefreshToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminrefreshtoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case adminrefreshtoken.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case adminrefreshtoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case adminrefreshtoken.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		case adminrefreshtoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case adminrefreshtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case adminrefreshtoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case adminrefreshtoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_user_refresh_tokens", values[i])
			} else if value.Valid {
				_m.admin_user_refresh_tokens = new(string)
				*_m.admin_user_refresh_tokens = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminRefreshToken.
// This includes values selected through modifiers, order, etc.
func (_m *AdminRefreshToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdminUser queries the "admin_user" edge of the AdminRefreshToken entity.
func (_m *AdminRefreshToken) QueryAdminUser() *AdminUserQuery {
	return NewAdminRefreshTokenClient(_m.config).QueryAdminUser(_m)
}

// Update returns a builder for updating this AdminRefreshToken.
// Note that you need to call AdminRefreshToken.Unwrap() before calling this method if this AdminRefreshToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminRefreshToken) Update() *AdminRefreshTokenUpdateOne {
	return NewAdminRefreshTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminRefreshToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminRefreshToken) Unwrap() *AdminRefreshToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminRefreshToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminRefreshToken) String() string {
	var builder strings.Builder
	builder.WriteString("AdminRefreshToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AdminRefreshTokens is a parsable slice of AdminRefreshToken.
type AdminRefreshTokens []*AdminRefreshToken
