// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoLabra/labra/entgql/ent/adminuser"
	"github.com/GoLabra/labra/entgql/ent/role"
)

// AdminUser is the model entity for the AdminUser schema.
type AdminUser struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// ActivationKey holds the value of the "activation_key" field.
	ActivationKey *string `json:"activation_key,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminUserQuery when eager-loading is set.
	Edges                       AdminUserEdges `json:"edges"`
	admin_user_admin_created_by *string
	admin_user_admin_updated_by *string
	admin_user_default_role     *string
	selectValues                sql.SelectValues
}

// AdminUserEdges holds the relations/edges for other nodes in the graph.
type AdminUserEdges struct {
	// RefAdminCreatedBy holds the value of the ref_admin_created_by edge.
	RefAdminCreatedBy []*AdminUser `json:"ref_admin_created_by,omitempty"`
	// AdminCreatedBy holds the value of the admin_created_by edge.
	AdminCreatedBy *AdminUser `json:"admin_created_by,omitempty"`
	// RefAdminUpdatedBy holds the value of the ref_admin_updated_by edge.
	RefAdminUpdatedBy []*AdminUser `json:"ref_admin_updated_by,omitempty"`
	// AdminUpdatedBy holds the value of the admin_updated_by edge.
	AdminUpdatedBy *AdminUser `json:"admin_updated_by,omitempty"`
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// DefaultRole holds the value of the default_role edge.
	DefaultRole *Role `json:"default_role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
	// totalCount holds the count of the edges above.
	totalCount [5]map[string]int

	namedRefAdminCreatedBy map[string][]*AdminUser
	namedRefAdminUpdatedBy map[string][]*AdminUser
	namedRoles             map[string][]*Role
}

// RefAdminCreatedByOrErr returns the RefAdminCreatedBy value or an error if the edge
// was not loaded in eager-loading.
func (e AdminUserEdges) RefAdminCreatedByOrErr() ([]*AdminUser, error) {
	if e.loadedTypes[0] {
		return e.RefAdminCreatedBy, nil
	}
	return nil, &NotLoadedError{edge: "ref_admin_created_by"}
}

// AdminCreatedByOrErr returns the AdminCreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminUserEdges) AdminCreatedByOrErr() (*AdminUser, error) {
	if e.AdminCreatedBy != nil {
		return e.AdminCreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "admin_created_by"}
}

// RefAdminUpdatedByOrErr returns the RefAdminUpdatedBy value or an error if the edge
// was not loaded in eager-loading.
func (e AdminUserEdges) RefAdminUpdatedByOrErr() ([]*AdminUser, error) {
	if e.loadedTypes[2] {
		return e.RefAdminUpdatedBy, nil
	}
	return nil, &NotLoadedError{edge: "ref_admin_updated_by"}
}

// AdminUpdatedByOrErr returns the AdminUpdatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminUserEdges) AdminUpdatedByOrErr() (*AdminUser, error) {
	if e.AdminUpdatedBy != nil {
		return e.AdminUpdatedBy, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: adminuser.Label}
	}
	return nil, &NotLoadedError{edge: "admin_updated_by"}
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e AdminUserEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[4] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// DefaultRoleOrErr returns the DefaultRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminUserEdges) DefaultRoleOrErr() (*Role, error) {
	if e.DefaultRole != nil {
		return e.DefaultRole, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "default_role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminuser.FieldID, adminuser.FieldName, adminuser.FieldEmail, adminuser.FieldPassword, adminuser.FieldActivationKey, adminuser.FieldFirstName, adminuser.FieldLastName:
			values[i] = new(sql.NullString)
		case adminuser.FieldCreatedAt, adminuser.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case adminuser.ForeignKeys[0]: // admin_user_admin_created_by
			values[i] = new(sql.NullString)
		case adminuser.ForeignKeys[1]: // admin_user_admin_updated_by
			values[i] = new(sql.NullString)
		case adminuser.ForeignKeys[2]: // admin_user_default_role
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminUser fields.
func (au *AdminUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminuser.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				au.ID = value.String
			}
		case adminuser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				au.Name = value.String
			}
		case adminuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				au.Email = value.String
			}
		case adminuser.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				au.Password = value.String
			}
		case adminuser.FieldActivationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field activation_key", values[i])
			} else if value.Valid {
				au.ActivationKey = new(string)
				*au.ActivationKey = value.String
			}
		case adminuser.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				au.FirstName = value.String
			}
		case adminuser.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				au.LastName = value.String
			}
		case adminuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				au.CreatedAt = new(time.Time)
				*au.CreatedAt = value.Time
			}
		case adminuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				au.UpdatedAt = new(time.Time)
				*au.UpdatedAt = value.Time
			}
		case adminuser.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_user_admin_created_by", values[i])
			} else if value.Valid {
				au.admin_user_admin_created_by = new(string)
				*au.admin_user_admin_created_by = value.String
			}
		case adminuser.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_user_admin_updated_by", values[i])
			} else if value.Valid {
				au.admin_user_admin_updated_by = new(string)
				*au.admin_user_admin_updated_by = value.String
			}
		case adminuser.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_user_default_role", values[i])
			} else if value.Valid {
				au.admin_user_default_role = new(string)
				*au.admin_user_default_role = value.String
			}
		default:
			au.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminUser.
// This includes values selected through modifiers, order, etc.
func (au *AdminUser) Value(name string) (ent.Value, error) {
	return au.selectValues.Get(name)
}

// QueryRefAdminCreatedBy queries the "ref_admin_created_by" edge of the AdminUser entity.
func (au *AdminUser) QueryRefAdminCreatedBy() *AdminUserQuery {
	return NewAdminUserClient(au.config).QueryRefAdminCreatedBy(au)
}

// QueryAdminCreatedBy queries the "admin_created_by" edge of the AdminUser entity.
func (au *AdminUser) QueryAdminCreatedBy() *AdminUserQuery {
	return NewAdminUserClient(au.config).QueryAdminCreatedBy(au)
}

// QueryRefAdminUpdatedBy queries the "ref_admin_updated_by" edge of the AdminUser entity.
func (au *AdminUser) QueryRefAdminUpdatedBy() *AdminUserQuery {
	return NewAdminUserClient(au.config).QueryRefAdminUpdatedBy(au)
}

// QueryAdminUpdatedBy queries the "admin_updated_by" edge of the AdminUser entity.
func (au *AdminUser) QueryAdminUpdatedBy() *AdminUserQuery {
	return NewAdminUserClient(au.config).QueryAdminUpdatedBy(au)
}

// QueryRoles queries the "roles" edge of the AdminUser entity.
func (au *AdminUser) QueryRoles() *RoleQuery {
	return NewAdminUserClient(au.config).QueryRoles(au)
}

// QueryDefaultRole queries the "default_role" edge of the AdminUser entity.
func (au *AdminUser) QueryDefaultRole() *RoleQuery {
	return NewAdminUserClient(au.config).QueryDefaultRole(au)
}

// Update returns a builder for updating this AdminUser.
// Note that you need to call AdminUser.Unwrap() before calling this method if this AdminUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (au *AdminUser) Update() *AdminUserUpdateOne {
	return NewAdminUserClient(au.config).UpdateOne(au)
}

// Unwrap unwraps the AdminUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (au *AdminUser) Unwrap() *AdminUser {
	_tx, ok := au.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminUser is not a transactional entity")
	}
	au.config.driver = _tx.drv
	return au
}

// String implements the fmt.Stringer.
func (au *AdminUser) String() string {
	var builder strings.Builder
	builder.WriteString("AdminUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", au.ID))
	builder.WriteString("name=")
	builder.WriteString(au.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(au.Email)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(au.Password)
	builder.WriteString(", ")
	if v := au.ActivationKey; v != nil {
		builder.WriteString("activation_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("first_name=")
	builder.WriteString(au.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(au.LastName)
	builder.WriteString(", ")
	if v := au.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := au.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedRefAdminCreatedBy returns the RefAdminCreatedBy named value or an error if the edge was not
// loaded in eager-loading with this name.
func (au *AdminUser) NamedRefAdminCreatedBy(name string) ([]*AdminUser, error) {
	if au.Edges.namedRefAdminCreatedBy == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := au.Edges.namedRefAdminCreatedBy[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (au *AdminUser) appendNamedRefAdminCreatedBy(name string, edges ...*AdminUser) {
	if au.Edges.namedRefAdminCreatedBy == nil {
		au.Edges.namedRefAdminCreatedBy = make(map[string][]*AdminUser)
	}
	if len(edges) == 0 {
		au.Edges.namedRefAdminCreatedBy[name] = []*AdminUser{}
	} else {
		au.Edges.namedRefAdminCreatedBy[name] = append(au.Edges.namedRefAdminCreatedBy[name], edges...)
	}
}

// NamedRefAdminUpdatedBy returns the RefAdminUpdatedBy named value or an error if the edge was not
// loaded in eager-loading with this name.
func (au *AdminUser) NamedRefAdminUpdatedBy(name string) ([]*AdminUser, error) {
	if au.Edges.namedRefAdminUpdatedBy == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := au.Edges.namedRefAdminUpdatedBy[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (au *AdminUser) appendNamedRefAdminUpdatedBy(name string, edges ...*AdminUser) {
	if au.Edges.namedRefAdminUpdatedBy == nil {
		au.Edges.namedRefAdminUpdatedBy = make(map[string][]*AdminUser)
	}
	if len(edges) == 0 {
		au.Edges.namedRefAdminUpdatedBy[name] = []*AdminUser{}
	} else {
		au.Edges.namedRefAdminUpdatedBy[name] = append(au.Edges.namedRefAdminUpdatedBy[name], edges...)
	}
}

// NamedRoles returns the Roles named value or an error if the edge was not
// loaded in eager-loading with this name.
func (au *AdminUser) NamedRoles(name string) ([]*Role, error) {
	if au.Edges.namedRoles == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := au.Edges.namedRoles[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (au *AdminUser) appendNamedRoles(name string, edges ...*Role) {
	if au.Edges.namedRoles == nil {
		au.Edges.namedRoles = make(map[string][]*Role)
	}
	if len(edges) == 0 {
		au.Edges.namedRoles[name] = []*Role{}
	} else {
		au.Edges.namedRoles[name] = append(au.Edges.namedRoles[name], edges...)
	}
}

// AdminUsers is a parsable slice of AdminUser.
type AdminUsers []*AdminUser
