// Code generated by internal template, DO NOT EDIT.

package ent

import (
	"fmt"

	"github.com/GoLabra/labra/entgql/ent/adminuser"
	"github.com/GoLabra/labra/entgql/ent/file"
	"github.com/GoLabra/labra/entgql/ent/permission"
	"github.com/GoLabra/labra/entgql/ent/role"
	"github.com/GoLabra/labra/entgql/ent/user"
)

// SetEdge sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *AdminUserMutation) SetEdge(name, value string) error {
	switch name {
	case adminuser.EdgeAdminCreatedBy:
		m.SetAdminCreatedByID(value)
		return nil
	case adminuser.EdgeAdminUpdatedBy:
		m.SetAdminUpdatedByID(value)
		return nil
	case adminuser.EdgeDefaultRole:
		m.SetDefaultRoleID(value)
		return nil
	}
	return fmt.Errorf("unknown AdminUser edge %s", name)
}

// SetEdge sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *FileMutation) SetEdge(name, value string) error {
	switch name {
	case file.EdgeAdminCreatedBy:
		m.SetAdminCreatedByID(value)
		return nil
	case file.EdgeAdminUpdatedBy:
		m.SetAdminUpdatedByID(value)
		return nil
	case file.EdgeCreatedBy:
		m.SetCreatedByID(value)
		return nil
	case file.EdgeUpdatedBy:
		m.SetUpdatedByID(value)
		return nil
	}
	return fmt.Errorf("unknown File edge %s", name)
}

// SetEdge sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *PermissionMutation) SetEdge(name, value string) error {
	switch name {
	case permission.EdgeAdminCreatedBy:
		m.SetAdminCreatedByID(value)
		return nil
	case permission.EdgeAdminUpdatedBy:
		m.SetAdminUpdatedByID(value)
		return nil
	case permission.EdgeRole:
		m.SetRoleID(value)
		return nil
	}
	return fmt.Errorf("unknown Permission edge %s", name)
}

// SetEdge sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *RoleMutation) SetEdge(name, value string) error {
	switch name {
	case role.EdgeAdminCreatedBy:
		m.SetAdminCreatedByID(value)
		return nil
	case role.EdgeAdminUpdatedBy:
		m.SetAdminUpdatedByID(value)
		return nil
	}
	return fmt.Errorf("unknown Role edge %s", name)
}

// SetEdge sets the value of a field with the given name. It returns an error if
// the edge is not defined in the schema
func (m *UserMutation) SetEdge(name, value string) error {
	switch name {
	case user.EdgeCreatedBy:
		m.SetCreatedByID(value)
		return nil
	case user.EdgeUpdatedBy:
		m.SetUpdatedByID(value)
		return nil
	case user.EdgeAdminCreatedBy:
		m.SetAdminCreatedByID(value)
		return nil
	case user.EdgeAdminUpdatedBy:
		m.SetAdminUpdatedByID(value)
		return nil
	case user.EdgeDefaultRole:
		m.SetDefaultRoleID(value)
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
