// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoLabra/labra/entgql/ent/adminuser"
	"github.com/GoLabra/labra/entgql/ent/permission"
	"github.com/GoLabra/labra/entgql/ent/predicate"
	"github.com/GoLabra/labra/entgql/ent/role"
)

// PermissionUpdate is the builder for updating Permission entities.
type PermissionUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionMutation
}

// Where appends a list predicates to the PermissionUpdate builder.
func (pu *PermissionUpdate) Where(ps ...predicate.Permission) *PermissionUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetCreatedAt sets the "created_at" field.
func (pu *PermissionUpdate) SetCreatedAt(t time.Time) *PermissionUpdate {
	pu.mutation.SetCreatedAt(t)
	return pu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pu *PermissionUpdate) SetNillableCreatedAt(t *time.Time) *PermissionUpdate {
	if t != nil {
		pu.SetCreatedAt(*t)
	}
	return pu
}

// ClearCreatedAt clears the value of the "created_at" field.
func (pu *PermissionUpdate) ClearCreatedAt() *PermissionUpdate {
	pu.mutation.ClearCreatedAt()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PermissionUpdate) SetUpdatedAt(t time.Time) *PermissionUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (pu *PermissionUpdate) ClearUpdatedAt() *PermissionUpdate {
	pu.mutation.ClearUpdatedAt()
	return pu
}

// SetEntity sets the "entity" field.
func (pu *PermissionUpdate) SetEntity(s string) *PermissionUpdate {
	pu.mutation.SetEntity(s)
	return pu
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (pu *PermissionUpdate) SetNillableEntity(s *string) *PermissionUpdate {
	if s != nil {
		pu.SetEntity(*s)
	}
	return pu
}

// SetOperation sets the "operation" field.
func (pu *PermissionUpdate) SetOperation(s string) *PermissionUpdate {
	pu.mutation.SetOperation(s)
	return pu
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (pu *PermissionUpdate) SetNillableOperation(s *string) *PermissionUpdate {
	if s != nil {
		pu.SetOperation(*s)
	}
	return pu
}

// SetAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID.
func (pu *PermissionUpdate) SetAdminCreatedByID(id string) *PermissionUpdate {
	pu.mutation.SetAdminCreatedByID(id)
	return pu
}

// SetNillableAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID if the given value is not nil.
func (pu *PermissionUpdate) SetNillableAdminCreatedByID(id *string) *PermissionUpdate {
	if id != nil {
		pu = pu.SetAdminCreatedByID(*id)
	}
	return pu
}

// SetAdminCreatedBy sets the "admin_created_by" edge to the AdminUser entity.
func (pu *PermissionUpdate) SetAdminCreatedBy(a *AdminUser) *PermissionUpdate {
	return pu.SetAdminCreatedByID(a.ID)
}

// SetAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID.
func (pu *PermissionUpdate) SetAdminUpdatedByID(id string) *PermissionUpdate {
	pu.mutation.SetAdminUpdatedByID(id)
	return pu
}

// SetNillableAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID if the given value is not nil.
func (pu *PermissionUpdate) SetNillableAdminUpdatedByID(id *string) *PermissionUpdate {
	if id != nil {
		pu = pu.SetAdminUpdatedByID(*id)
	}
	return pu
}

// SetAdminUpdatedBy sets the "admin_updated_by" edge to the AdminUser entity.
func (pu *PermissionUpdate) SetAdminUpdatedBy(a *AdminUser) *PermissionUpdate {
	return pu.SetAdminUpdatedByID(a.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (pu *PermissionUpdate) SetRoleID(id string) *PermissionUpdate {
	pu.mutation.SetRoleID(id)
	return pu
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (pu *PermissionUpdate) SetNillableRoleID(id *string) *PermissionUpdate {
	if id != nil {
		pu = pu.SetRoleID(*id)
	}
	return pu
}

// SetRole sets the "role" edge to the Role entity.
func (pu *PermissionUpdate) SetRole(r *Role) *PermissionUpdate {
	return pu.SetRoleID(r.ID)
}

// Mutation returns the PermissionMutation object of the builder.
func (pu *PermissionUpdate) Mutation() *PermissionMutation {
	return pu.mutation
}

// ClearAdminCreatedBy clears the "admin_created_by" edge to the AdminUser entity.
func (pu *PermissionUpdate) ClearAdminCreatedBy() *PermissionUpdate {
	pu.mutation.ClearAdminCreatedBy()
	return pu
}

// ClearAdminUpdatedBy clears the "admin_updated_by" edge to the AdminUser entity.
func (pu *PermissionUpdate) ClearAdminUpdatedBy() *PermissionUpdate {
	pu.mutation.ClearAdminUpdatedBy()
	return pu
}

// ClearRole clears the "role" edge to the Role entity.
func (pu *PermissionUpdate) ClearRole() *PermissionUpdate {
	pu.mutation.ClearRole()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PermissionUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PermissionUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PermissionUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PermissionUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok && !pu.mutation.UpdatedAtCleared() {
		v := permission.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PermissionUpdate) check() error {
	if v, ok := pu.mutation.Operation(); ok {
		if err := permission.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Permission.operation": %w`, err)}
		}
	}
	return nil
}

func (pu *PermissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.CreatedAt(); ok {
		_spec.SetField(permission.FieldCreatedAt, field.TypeTime, value)
	}
	if pu.mutation.CreatedAtCleared() {
		_spec.ClearField(permission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.UpdatedAtCleared() {
		_spec.ClearField(permission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.Entity(); ok {
		_spec.SetField(permission.FieldEntity, field.TypeString, value)
	}
	if value, ok := pu.mutation.Operation(); ok {
		_spec.SetField(permission.FieldOperation, field.TypeString, value)
	}
	if pu.mutation.AdminCreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminCreatedByTable,
			Columns: []string{permission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AdminCreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminCreatedByTable,
			Columns: []string{permission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.AdminUpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminUpdatedByTable,
			Columns: []string{permission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AdminUpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminUpdatedByTable,
			Columns: []string{permission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PermissionUpdateOne is the builder for updating a single Permission entity.
type PermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionMutation
}

// SetCreatedAt sets the "created_at" field.
func (puo *PermissionUpdateOne) SetCreatedAt(t time.Time) *PermissionUpdateOne {
	puo.mutation.SetCreatedAt(t)
	return puo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableCreatedAt(t *time.Time) *PermissionUpdateOne {
	if t != nil {
		puo.SetCreatedAt(*t)
	}
	return puo
}

// ClearCreatedAt clears the value of the "created_at" field.
func (puo *PermissionUpdateOne) ClearCreatedAt() *PermissionUpdateOne {
	puo.mutation.ClearCreatedAt()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PermissionUpdateOne) SetUpdatedAt(t time.Time) *PermissionUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (puo *PermissionUpdateOne) ClearUpdatedAt() *PermissionUpdateOne {
	puo.mutation.ClearUpdatedAt()
	return puo
}

// SetEntity sets the "entity" field.
func (puo *PermissionUpdateOne) SetEntity(s string) *PermissionUpdateOne {
	puo.mutation.SetEntity(s)
	return puo
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableEntity(s *string) *PermissionUpdateOne {
	if s != nil {
		puo.SetEntity(*s)
	}
	return puo
}

// SetOperation sets the "operation" field.
func (puo *PermissionUpdateOne) SetOperation(s string) *PermissionUpdateOne {
	puo.mutation.SetOperation(s)
	return puo
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableOperation(s *string) *PermissionUpdateOne {
	if s != nil {
		puo.SetOperation(*s)
	}
	return puo
}

// SetAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID.
func (puo *PermissionUpdateOne) SetAdminCreatedByID(id string) *PermissionUpdateOne {
	puo.mutation.SetAdminCreatedByID(id)
	return puo
}

// SetNillableAdminCreatedByID sets the "admin_created_by" edge to the AdminUser entity by ID if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableAdminCreatedByID(id *string) *PermissionUpdateOne {
	if id != nil {
		puo = puo.SetAdminCreatedByID(*id)
	}
	return puo
}

// SetAdminCreatedBy sets the "admin_created_by" edge to the AdminUser entity.
func (puo *PermissionUpdateOne) SetAdminCreatedBy(a *AdminUser) *PermissionUpdateOne {
	return puo.SetAdminCreatedByID(a.ID)
}

// SetAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID.
func (puo *PermissionUpdateOne) SetAdminUpdatedByID(id string) *PermissionUpdateOne {
	puo.mutation.SetAdminUpdatedByID(id)
	return puo
}

// SetNillableAdminUpdatedByID sets the "admin_updated_by" edge to the AdminUser entity by ID if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableAdminUpdatedByID(id *string) *PermissionUpdateOne {
	if id != nil {
		puo = puo.SetAdminUpdatedByID(*id)
	}
	return puo
}

// SetAdminUpdatedBy sets the "admin_updated_by" edge to the AdminUser entity.
func (puo *PermissionUpdateOne) SetAdminUpdatedBy(a *AdminUser) *PermissionUpdateOne {
	return puo.SetAdminUpdatedByID(a.ID)
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (puo *PermissionUpdateOne) SetRoleID(id string) *PermissionUpdateOne {
	puo.mutation.SetRoleID(id)
	return puo
}

// SetNillableRoleID sets the "role" edge to the Role entity by ID if the given value is not nil.
func (puo *PermissionUpdateOne) SetNillableRoleID(id *string) *PermissionUpdateOne {
	if id != nil {
		puo = puo.SetRoleID(*id)
	}
	return puo
}

// SetRole sets the "role" edge to the Role entity.
func (puo *PermissionUpdateOne) SetRole(r *Role) *PermissionUpdateOne {
	return puo.SetRoleID(r.ID)
}

// Mutation returns the PermissionMutation object of the builder.
func (puo *PermissionUpdateOne) Mutation() *PermissionMutation {
	return puo.mutation
}

// ClearAdminCreatedBy clears the "admin_created_by" edge to the AdminUser entity.
func (puo *PermissionUpdateOne) ClearAdminCreatedBy() *PermissionUpdateOne {
	puo.mutation.ClearAdminCreatedBy()
	return puo
}

// ClearAdminUpdatedBy clears the "admin_updated_by" edge to the AdminUser entity.
func (puo *PermissionUpdateOne) ClearAdminUpdatedBy() *PermissionUpdateOne {
	puo.mutation.ClearAdminUpdatedBy()
	return puo
}

// ClearRole clears the "role" edge to the Role entity.
func (puo *PermissionUpdateOne) ClearRole() *PermissionUpdateOne {
	puo.mutation.ClearRole()
	return puo
}

// Where appends a list predicates to the PermissionUpdate builder.
func (puo *PermissionUpdateOne) Where(ps ...predicate.Permission) *PermissionUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PermissionUpdateOne) Select(field string, fields ...string) *PermissionUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Permission entity.
func (puo *PermissionUpdateOne) Save(ctx context.Context) (*Permission, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PermissionUpdateOne) SaveX(ctx context.Context) *Permission {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PermissionUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PermissionUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok && !puo.mutation.UpdatedAtCleared() {
		v := permission.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PermissionUpdateOne) check() error {
	if v, ok := puo.mutation.Operation(); ok {
		if err := permission.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "Permission.operation": %w`, err)}
		}
	}
	return nil
}

func (puo *PermissionUpdateOne) sqlSave(ctx context.Context) (_node *Permission, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permission.Table, permission.Columns, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permission.FieldID)
		for _, f := range fields {
			if !permission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.CreatedAt(); ok {
		_spec.SetField(permission.FieldCreatedAt, field.TypeTime, value)
	}
	if puo.mutation.CreatedAtCleared() {
		_spec.ClearField(permission.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.UpdatedAtCleared() {
		_spec.ClearField(permission.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.Entity(); ok {
		_spec.SetField(permission.FieldEntity, field.TypeString, value)
	}
	if value, ok := puo.mutation.Operation(); ok {
		_spec.SetField(permission.FieldOperation, field.TypeString, value)
	}
	if puo.mutation.AdminCreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminCreatedByTable,
			Columns: []string{permission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AdminCreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminCreatedByTable,
			Columns: []string{permission.AdminCreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.AdminUpdatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminUpdatedByTable,
			Columns: []string{permission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AdminUpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.AdminUpdatedByTable,
			Columns: []string{permission.AdminUpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   permission.RoleTable,
			Columns: []string{permission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Permission{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
